name: mysejahtera_plus
description: A clone app of MySejahtera (Official App from Minister of Education in Malaysia).

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # List of dependecies used in the app
  bloc: ^8.0.3 # State Management package - https://pub.dev/packages/bloc
  flutter_bloc: ^8.0.1 # BLoC for Flutter - https://pub.dev/packages/flutter_bloc
  connectivity_plus: ^2.2.1 # To check network connectivity - https://pub.dev/packages/connectivity_plus
  animations: ^2.0.2 # Add animation to widget like Hero - https://pub.dev/packages/animations
  salomon_bottom_bar: ^3.3.0 # Bottom navigation bar - https://pub.dev/packages/salomon_bottom_bar
  dropdown_button2: ^1.2.2 # Better dropdown menu - https://pub.dev/packages/dropdown_button2
  google_fonts: ^2.3.1 # Dynamic font package - https://pub.dev/packages/google_fonts
  responsive_framework: ^0.1.7 # Easy responsive UI - https://pub.dev/packages/responsive_framework
  qr_flutter: ^4.0.0 # Generate QR code - https://pub.dev/packages/qr_flutter
  # TODO: QR code iOS configuration
  mobile_scanner: ^1.0.0 # QR code scanner - https://pub.dev/packages/mobile_scanner

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

  # List of dependecies used in development
  device_preview: ^1.0.0 # To preview app on different devices - https://pub.dev/packages/device_preview

flutter:
  uses-material-design: true
  assets:
    - asset/images/
  fonts:
    - family: CheckInIcons
      fonts:
        - asset: fonts/CheckInIcons.ttf