import 'package:flutter/material.dart';

import '../../data_layers/models/statistics_states_model.dart';
import '../../data_layers/repositories/statistics_states_repositories.dart';
import '../../helper/constant.dart';
import 'grid_statistics_states_items.dart';

class GridStatisticsStates extends StatefulWidget {
  const GridStatisticsStates({Key? key, required this.time}) : super(key: key);

  final String time;

  @override
  State<GridStatisticsStates> createState() => _GridStatisticsStatesState();
}

class _GridStatisticsStatesState extends State<GridStatisticsStates> {

  //! NOT SURE HOW TO USE REPO FOR THIS, reason => always return empty List

  // StatisticsDataStatesRepositories repo = StatisticsDataStatesRepositories();

  // dynamic dataList;

  // @override
  // void initState() {
  //   dataList = repo.fetchStatesData();
  //   super.initState();
  // }

  // @override
  // Widget build(BuildContext context) {
  //   return FutureBuilder(
  //       future: dataList,
  //       builder: (context, AsyncSnapshot<List<List>> snapshot) {
  //         if (snapshot.connectionState == ConnectionState.done) {
  //           return ListView(
  //             children: [
  //               StatisticsStatesItems(
  //                 titleText: 'Johor',
  //                 // TOP LEFT
  //                 topLeftColor: kStatisticRed,
  //                 topLeftHeader: 'Total Confirmed Cases',
  //                 topLeftTotalText: snapshot.data![0][0].cardConfirmedModel.caseConfirmed,
  //                 topLeftPlusOrMinus: snapshot.data![0][0].cardConfirmedModel.caseConfirmedPlus,
  //                 topLeftTodayText: snapshot.data![0][0].cardConfirmedModel.caseConfirmedToday,
  //                 topLeftUpOrDown: snapshot.data![0][0].cardConfirmedModel.caseConfirmedArrow,
  //                 topLeftPercentage: snapshot.data![0][0].cardConfirmedModel.caseConfirmedPercent,
  //                 topLeftDate: widget.time,
  //                 // TOP RIGHT
  //                 topRightColor: kStatisticGreen,
  //                 topRightHeader: 'Total Recovered',
  //                 topRightTotalText: snapshot.data![0][1].cardRecoveredModel.caseRecovered,
  //                 topRightPlusOrMinus: snapshot.data![0][1].cardRecoveredModel.caseRecoveredPlus,
  //                 topRightTodayText: snapshot.data![0][1].cardRecoveredModel.caseRecoveredToday,
  //                 topRightUpOrDown: snapshot.data![0][1].cardRecoveredModel.caseRecoveredArrow,
  //                 topRightPercentage: snapshot.data![0][1].cardRecoveredModel.caseRecoveredPercent,
  //                 topRightDate: widget.time,
  //                 // BOTTOM LEFT
  //                 bottomLeftColor: kStatisticGrey,
  //                 bottomLeftHeader: 'Total Death',
  //                 bottomLeftTotalText: snapshot.data![0][2].cardDeathModel.caseDeath,
  //                 bottomLeftPlusOrMinus: snapshot.data![0][2].cardDeathModel.caseDeathPlus,
  //                 bottomLeftTodayText: snapshot.data![0][2].cardDeathModel.caseDeathToday,
  //                 bottomLeftUpOrDown: snapshot.data![0][2].cardDeathModel.caseDeathArrow,
  //                 bottomLeftPercentage: snapshot.data![0][2].cardDeathModel.caseDeathPercent,
  //                 bottomLeftDate: widget.time,
  //                 // BOTTOM RIGHT
  //                 bottomRightColor: kStatisticOrange,
  //                 bottomRightHeader: 'Total Active Cases',
  //                 bottomRightTotalText: snapshot.data![0][3].cardActiveModel.caseActive,
  //                 bottomRightPlusOrMinus: snapshot.data![0][3].cardActiveModel.caseActivePlus,
  //                 bottomRightTodayText: snapshot.data![0][3].cardActiveModel.caseActiveToday,
  //                 bottomRightUpOrDown: snapshot.data![0][3].cardActiveModel.caseActiveArrow,
  //                 bottomRightPercentage: snapshot.data![0][3].cardActiveModel.caseActivePercent,
  //                 bottomRightDate: widget.time,
  //               ),
  //               StatisticsStatesItems(
  //                 titleText: 'Kedah',
  //                 // TOP LEFT
  //                 topLeftColor: kStatisticRed,
  //                 topLeftHeader: 'Total Confirmed Cases',
  //                 topLeftTotalText: snapshot.data![1][0].cardConfirmedModel.caseConfirmed,
  //                 topLeftPlusOrMinus: snapshot.data![1][0].cardConfirmedModel.caseConfirmedPlus,
  //                 topLeftTodayText: snapshot.data![1][0].cardConfirmedModel.caseConfirmedToday,
  //                 topLeftUpOrDown: snapshot.data![1][0].cardConfirmedModel.caseConfirmedArrow,
  //                 topLeftPercentage: snapshot.data![1][0].cardConfirmedModel.caseConfirmedPercent,
  //                 topLeftDate: widget.time,
  //                 // TOP RIGHT
  //                 topRightColor: kStatisticGreen,
  //                 topRightHeader: 'Total Recovered',
  //                 topRightTotalText: snapshot.data![1][1].cardRecoveredModel.caseRecovered,
  //                 topRightPlusOrMinus: snapshot.data![1][1].cardRecoveredModel.caseRecoveredPlus,
  //                 topRightTodayText: snapshot.data![1][1].cardRecoveredModel.caseRecoveredToday,
  //                 topRightUpOrDown: snapshot.data![1][1].cardRecoveredModel.caseRecoveredArrow,
  //                 topRightPercentage: snapshot.data![1][1].cardRecoveredModel.caseRecoveredPercent,
  //                 topRightDate: widget.time,
  //                 // BOTTOM LEFT
  //                 bottomLeftColor: kStatisticGrey,
  //                 bottomLeftHeader: 'Total Death',
  //                 bottomLeftTotalText: snapshot.data![1][2].cardDeathModel.caseDeath,
  //                 bottomLeftPlusOrMinus: snapshot.data![1][2].cardDeathModel.caseDeathPlus,
  //                 bottomLeftTodayText: snapshot.data![1][2].cardDeathModel.caseDeathToday,
  //                 bottomLeftUpOrDown: snapshot.data![1][2].cardDeathModel.caseDeathArrow,
  //                 bottomLeftPercentage: snapshot.data![1][2].cardDeathModel.caseDeathPercent,
  //                 bottomLeftDate: widget.time,
  //                 // BOTTOM RIGHT
  //                 bottomRightColor: kStatisticOrange,
  //                 bottomRightHeader: 'Total Active Cases',
  //                 bottomRightTotalText: snapshot.data![1][3].cardActiveModel.caseActive,
  //                 bottomRightPlusOrMinus: snapshot.data![1][3].cardActiveModel.caseActivePlus,
  //                 bottomRightTodayText: snapshot.data![1][3].cardActiveModel.caseActiveToday,
  //                 bottomRightUpOrDown: snapshot.data![1][3].cardActiveModel.caseActiveArrow,
  //                 bottomRightPercentage: snapshot.data![1][3].cardActiveModel.caseActivePercent,
  //                 bottomRightDate: widget.time,
  //               ),
  //               StatisticsStatesItems(
  //                 titleText: 'Kelantan',
  //                 // TOP LEFT
  //                 topLeftColor: kStatisticRed,
  //                 topLeftHeader: 'Total Confirmed Cases',
  //                 topLeftTotalText: snapshot.data![2][0].cardConfirmedModel.caseConfirmed,
  //                 topLeftPlusOrMinus: snapshot.data![2][0].cardConfirmedModel.caseConfirmedPlus,
  //                 topLeftTodayText: snapshot.data![2][0].cardConfirmedModel.caseConfirmedToday,
  //                 topLeftUpOrDown: snapshot.data![2][0].cardConfirmedModel.caseConfirmedArrow,
  //                 topLeftPercentage: snapshot.data![2][0].cardConfirmedModel.caseConfirmedPercent,
  //                 topLeftDate: widget.time,
  //                 // TOP RIGHT
  //                 topRightColor: kStatisticGreen,
  //                 topRightHeader: 'Total Recovered',
  //                 topRightTotalText: snapshot.data![2][1].cardRecoveredModel.caseRecovered,
  //                 topRightPlusOrMinus: snapshot.data![2][1].cardRecoveredModel.caseRecoveredPlus,
  //                 topRightTodayText: snapshot.data![2][1].cardRecoveredModel.caseRecoveredToday,
  //                 topRightUpOrDown: snapshot.data![2][1].cardRecoveredModel.caseRecoveredArrow,
  //                 topRightPercentage: snapshot.data![2][1].cardRecoveredModel.caseRecoveredPercent,
  //                 topRightDate: widget.time,
  //                 // BOTTOM LEFT
  //                 bottomLeftColor: kStatisticGrey,
  //                 bottomLeftHeader: 'Total Death',
  //                 bottomLeftTotalText: snapshot.data![2][2].cardDeathModel.caseDeath,
  //                 bottomLeftPlusOrMinus: snapshot.data![2][2].cardDeathModel.caseDeathPlus,
  //                 bottomLeftTodayText: snapshot.data![2][2].cardDeathModel.caseDeathToday,
  //                 bottomLeftUpOrDown: snapshot.data![2][2].cardDeathModel.caseDeathArrow,
  //                 bottomLeftPercentage: snapshot.data![2][2].cardDeathModel.caseDeathPercent,
  //                 bottomLeftDate: widget.time,
  //                 // BOTTOM RIGHT
  //                 bottomRightColor: kStatisticOrange,
  //                 bottomRightHeader: 'Total Active Cases',
  //                 bottomRightTotalText: snapshot.data![2][3].cardActiveModel.caseActive,
  //                 bottomRightPlusOrMinus: snapshot.data![2][3].cardActiveModel.caseActivePlus,
  //                 bottomRightTodayText: snapshot.data![2][3].cardActiveModel.caseActiveToday,
  //                 bottomRightUpOrDown: snapshot.data![2][3].cardActiveModel.caseActiveArrow,
  //                 bottomRightPercentage: snapshot.data![2][3].cardActiveModel.caseActivePercent,
  //                 bottomRightDate: widget.time,
  //               ),
  //               StatisticsStatesItems(
  //                 titleText: 'Malacca',
  //                 // TOP LEFT
  //                 topLeftColor: kStatisticRed,
  //                 topLeftHeader: 'Total Confirmed Cases',
  //                 topLeftTotalText: snapshot.data![3][0].cardConfirmedModel.caseConfirmed,
  //                 topLeftPlusOrMinus: snapshot.data![3][0].cardConfirmedModel.caseConfirmedPlus,
  //                 topLeftTodayText: snapshot.data![3][0].cardConfirmedModel.caseConfirmedToday,
  //                 topLeftUpOrDown: snapshot.data![3][0].cardConfirmedModel.caseConfirmedArrow,
  //                 topLeftPercentage: snapshot.data![3][0].cardConfirmedModel.caseConfirmedPercent,
  //                 topLeftDate: widget.time,
  //                 // TOP RIGHT
  //                 topRightColor: kStatisticGreen,
  //                 topRightHeader: 'Total Recovered',
  //                 topRightTotalText: snapshot.data![3][1].cardRecoveredModel.caseRecovered,
  //                 topRightPlusOrMinus: snapshot.data![3][1].cardRecoveredModel.caseRecoveredPlus,
  //                 topRightTodayText: snapshot.data![3][1].cardRecoveredModel.caseRecoveredToday,
  //                 topRightUpOrDown: snapshot.data![3][1].cardRecoveredModel.caseRecoveredArrow,
  //                 topRightPercentage: snapshot.data![3][1].cardRecoveredModel.caseRecoveredPercent,
  //                 topRightDate: widget.time,
  //                 // BOTTOM LEFT
  //                 bottomLeftColor: kStatisticGrey,
  //                 bottomLeftHeader: 'Total Death',
  //                 bottomLeftTotalText: snapshot.data![3][2].cardDeathModel.caseDeath,
  //                 bottomLeftPlusOrMinus: snapshot.data![3][2].cardDeathModel.caseDeathPlus,
  //                 bottomLeftTodayText: snapshot.data![3][2].cardDeathModel.caseDeathToday,
  //                 bottomLeftUpOrDown: snapshot.data![3][2].cardDeathModel.caseDeathArrow,
  //                 bottomLeftPercentage: snapshot.data![3][2].cardDeathModel.caseDeathPercent,
  //                 bottomLeftDate: widget.time,
  //                 // BOTTOM RIGHT
  //                 bottomRightColor: kStatisticOrange,
  //                 bottomRightHeader: 'Total Active Cases',
  //                 bottomRightTotalText: snapshot.data![3][3].cardActiveModel.caseActive,
  //                 bottomRightPlusOrMinus: snapshot.data![3][3].cardActiveModel.caseActivePlus,
  //                 bottomRightTodayText: snapshot.data![3][3].cardActiveModel.caseActiveToday,
  //                 bottomRightUpOrDown: snapshot.data![3][3].cardActiveModel.caseActiveArrow,
  //                 bottomRightPercentage: snapshot.data![3][3].cardActiveModel.caseActivePercent,
  //                 bottomRightDate: widget.time,
  //               ),
  //               StatisticsStatesItems(
  //                 titleText: 'Negeri Sembilan',
  //                 // TOP LEFT
  //                 topLeftColor: kStatisticRed,
  //                 topLeftHeader: 'Total Confirmed Cases',
  //                 topLeftTotalText: snapshot.data![4][0].cardConfirmedModel.caseConfirmed,
  //                 topLeftPlusOrMinus: snapshot.data![4][0].cardConfirmedModel.caseConfirmedPlus,
  //                 topLeftTodayText: snapshot.data![4][0].cardConfirmedModel.caseConfirmedToday,
  //                 topLeftUpOrDown: snapshot.data![4][0].cardConfirmedModel.caseConfirmedArrow,
  //                 topLeftPercentage: snapshot.data![4][0].cardConfirmedModel.caseConfirmedPercent,
  //                 topLeftDate: widget.time,
  //                 // TOP RIGHT
  //                 topRightColor: kStatisticGreen,
  //                 topRightHeader: 'Total Recovered',
  //                 topRightTotalText: snapshot.data![4][1].cardRecoveredModel.caseRecovered,
  //                 topRightPlusOrMinus: snapshot.data![4][1].cardRecoveredModel.caseRecoveredPlus,
  //                 topRightTodayText: snapshot.data![4][1].cardRecoveredModel.caseRecoveredToday,
  //                 topRightUpOrDown: snapshot.data![4][1].cardRecoveredModel.caseRecoveredArrow,
  //                 topRightPercentage: snapshot.data![4][1].cardRecoveredModel.caseRecoveredPercent,
  //                 topRightDate: widget.time,
  //                 // BOTTOM LEFT
  //                 bottomLeftColor: kStatisticGrey,
  //                 bottomLeftHeader: 'Total Death',
  //                 bottomLeftTotalText: snapshot.data![4][2].cardDeathModel.caseDeath,
  //                 bottomLeftPlusOrMinus: snapshot.data![4][2].cardDeathModel.caseDeathPlus,
  //                 bottomLeftTodayText: snapshot.data![4][2].cardDeathModel.caseDeathToday,
  //                 bottomLeftUpOrDown: snapshot.data![4][2].cardDeathModel.caseDeathArrow,
  //                 bottomLeftPercentage: snapshot.data![4][2].cardDeathModel.caseDeathPercent,
  //                 bottomLeftDate: widget.time,
  //                 // BOTTOM RIGHT
  //                 bottomRightColor: kStatisticOrange,
  //                 bottomRightHeader: 'Total Active Cases',
  //                 bottomRightTotalText: snapshot.data![4][3].cardActiveModel.caseActive,
  //                 bottomRightPlusOrMinus: snapshot.data![4][3].cardActiveModel.caseActivePlus,
  //                 bottomRightTodayText: snapshot.data![4][3].cardActiveModel.caseActiveToday,
  //                 bottomRightUpOrDown: snapshot.data![4][3].cardActiveModel.caseActiveArrow,
  //                 bottomRightPercentage: snapshot.data![4][3].cardActiveModel.caseActivePercent,
  //                 bottomRightDate: widget.time,
  //               ),
  //               StatisticsStatesItems(
  //                 titleText: 'Pahang',
  //                 // TOP LEFT
  //                 topLeftColor: kStatisticRed,
  //                 topLeftHeader: 'Total Confirmed Cases',
  //                 topLeftTotalText: snapshot.data![5][0].cardConfirmedModel.caseConfirmed,
  //                 topLeftPlusOrMinus: snapshot.data![5][0].cardConfirmedModel.caseConfirmedPlus,
  //                 topLeftTodayText: snapshot.data![5][0].cardConfirmedModel.caseConfirmedToday,
  //                 topLeftUpOrDown: snapshot.data![5][0].cardConfirmedModel.caseConfirmedArrow,
  //                 topLeftPercentage: snapshot.data![5][0].cardConfirmedModel.caseConfirmedPercent,
  //                 topLeftDate: widget.time,
  //                 // TOP RIGHT
  //                 topRightColor: kStatisticGreen,
  //                 topRightHeader: 'Total Recovered',
  //                 topRightTotalText: snapshot.data![5][1].cardRecoveredModel.caseRecovered,
  //                 topRightPlusOrMinus: snapshot.data![5][1].cardRecoveredModel.caseRecoveredPlus,
  //                 topRightTodayText: snapshot.data![5][1].cardRecoveredModel.caseRecoveredToday,
  //                 topRightUpOrDown: snapshot.data![5][1].cardRecoveredModel.caseRecoveredArrow,
  //                 topRightPercentage: snapshot.data![5][1].cardRecoveredModel.caseRecoveredPercent,
  //                 topRightDate: widget.time,
  //                 // BOTTOM LEFT
  //                 bottomLeftColor: kStatisticGrey,
  //                 bottomLeftHeader: 'Total Death',
  //                 bottomLeftTotalText: snapshot.data![5][2].cardDeathModel.caseDeath,
  //                 bottomLeftPlusOrMinus: snapshot.data![5][2].cardDeathModel.caseDeathPlus,
  //                 bottomLeftTodayText: snapshot.data![5][2].cardDeathModel.caseDeathToday,
  //                 bottomLeftUpOrDown: snapshot.data![5][2].cardDeathModel.caseDeathArrow,
  //                 bottomLeftPercentage: snapshot.data![5][2].cardDeathModel.caseDeathPercent,
  //                 bottomLeftDate: widget.time,
  //                 // BOTTOM RIGHT
  //                 bottomRightColor: kStatisticOrange,
  //                 bottomRightHeader: 'Total Active Cases',
  //                 bottomRightTotalText: snapshot.data![5][3].cardActiveModel.caseActive,
  //                 bottomRightPlusOrMinus: snapshot.data![5][3].cardActiveModel.caseActivePlus,
  //                 bottomRightTodayText: snapshot.data![5][3].cardActiveModel.caseActiveToday,
  //                 bottomRightUpOrDown: snapshot.data![5][3].cardActiveModel.caseActiveArrow,
  //                 bottomRightPercentage: snapshot.data![5][3].cardActiveModel.caseActivePercent,
  //                 bottomRightDate: widget.time,
  //               ),
  //               StatisticsStatesItems(
  //                 titleText: 'Penang',
  //                 // TOP LEFT
  //                 topLeftColor: kStatisticRed,
  //                 topLeftHeader: 'Total Confirmed Cases',
  //                 topLeftTotalText: snapshot.data![6][0].cardConfirmedModel.caseConfirmed,
  //                 topLeftPlusOrMinus: snapshot.data![6][0].cardConfirmedModel.caseConfirmedPlus,
  //                 topLeftTodayText: snapshot.data![6][0].cardConfirmedModel.caseConfirmedToday,
  //                 topLeftUpOrDown: snapshot.data![6][0].cardConfirmedModel.caseConfirmedArrow,
  //                 topLeftPercentage: snapshot.data![6][0].cardConfirmedModel.caseConfirmedPercent,
  //                 topLeftDate: widget.time,
  //                 // TOP RIGHT
  //                 topRightColor: kStatisticGreen,
  //                 topRightHeader: 'Total Recovered',
  //                 topRightTotalText: snapshot.data![6][1].cardRecoveredModel.caseRecovered,
  //                 topRightPlusOrMinus: snapshot.data![6][1].cardRecoveredModel.caseRecoveredPlus,
  //                 topRightTodayText: snapshot.data![6][1].cardRecoveredModel.caseRecoveredToday,
  //                 topRightUpOrDown: snapshot.data![6][1].cardRecoveredModel.caseRecoveredArrow,
  //                 topRightPercentage: snapshot.data![6][1].cardRecoveredModel.caseRecoveredPercent,
  //                 topRightDate: widget.time,
  //                 // BOTTOM LEFT
  //                 bottomLeftColor: kStatisticGrey,
  //                 bottomLeftHeader: 'Total Death',
  //                 bottomLeftTotalText: snapshot.data![6][2].cardDeathModel.caseDeath,
  //                 bottomLeftPlusOrMinus: snapshot.data![6][2].cardDeathModel.caseDeathPlus,
  //                 bottomLeftTodayText: snapshot.data![6][2].cardDeathModel.caseDeathToday,
  //                 bottomLeftUpOrDown: snapshot.data![6][2].cardDeathModel.caseDeathArrow,
  //                 bottomLeftPercentage: snapshot.data![6][2].cardDeathModel.caseDeathPercent,
  //                 bottomLeftDate: widget.time,
  //                 // BOTTOM RIGHT
  //                 bottomRightColor: kStatisticOrange,
  //                 bottomRightHeader: 'Total Active Cases',
  //                 bottomRightTotalText: snapshot.data![6][3].cardActiveModel.caseActive,
  //                 bottomRightPlusOrMinus: snapshot.data![6][3].cardActiveModel.caseActivePlus,
  //                 bottomRightTodayText: snapshot.data![6][3].cardActiveModel.caseActiveToday,
  //                 bottomRightUpOrDown: snapshot.data![6][3].cardActiveModel.caseActiveArrow,
  //                 bottomRightPercentage: snapshot.data![6][3].cardActiveModel.caseActivePercent,
  //                 bottomRightDate: widget.time,
  //               ),
  //               StatisticsStatesItems(
  //                 titleText: 'Perak',
  //                 // TOP LEFT
  //                 topLeftColor: kStatisticRed,
  //                 topLeftHeader: 'Total Confirmed Cases',
  //                 topLeftTotalText: snapshot.data![7][0].cardConfirmedModel.caseConfirmed,
  //                 topLeftPlusOrMinus: snapshot.data![7][0].cardConfirmedModel.caseConfirmedPlus,
  //                 topLeftTodayText: snapshot.data![7][0].cardConfirmedModel.caseConfirmedToday,
  //                 topLeftUpOrDown: snapshot.data![7][0].cardConfirmedModel.caseConfirmedArrow,
  //                 topLeftPercentage: snapshot.data![7][0].cardConfirmedModel.caseConfirmedPercent,
  //                 topLeftDate: widget.time,
  //                 // TOP RIGHT
  //                 topRightColor: kStatisticGreen,
  //                 topRightHeader: 'Total Recovered',
  //                 topRightTotalText: snapshot.data![7][1].cardRecoveredModel.caseRecovered,
  //                 topRightPlusOrMinus: snapshot.data![7][1].cardRecoveredModel.caseRecoveredPlus,
  //                 topRightTodayText: snapshot.data![7][1].cardRecoveredModel.caseRecoveredToday,
  //                 topRightUpOrDown: snapshot.data![7][1].cardRecoveredModel.caseRecoveredArrow,
  //                 topRightPercentage: snapshot.data![7][1].cardRecoveredModel.caseRecoveredPercent,
  //                 topRightDate: widget.time,
  //                 // BOTTOM LEFT
  //                 bottomLeftColor: kStatisticGrey,
  //                 bottomLeftHeader: 'Total Death',
  //                 bottomLeftTotalText: snapshot.data![7][2].cardDeathModel.caseDeath,
  //                 bottomLeftPlusOrMinus: snapshot.data![7][2].cardDeathModel.caseDeathPlus,
  //                 bottomLeftTodayText: snapshot.data![7][2].cardDeathModel.caseDeathToday,
  //                 bottomLeftUpOrDown: snapshot.data![7][2].cardDeathModel.caseDeathArrow,
  //                 bottomLeftPercentage: snapshot.data![7][2].cardDeathModel.caseDeathPercent,
  //                 bottomLeftDate: widget.time,
  //                 // BOTTOM RIGHT
  //                 bottomRightColor: kStatisticOrange,
  //                 bottomRightHeader: 'Total Active Cases',
  //                 bottomRightTotalText: snapshot.data![7][3].cardActiveModel.caseActive,
  //                 bottomRightPlusOrMinus: snapshot.data![7][3].cardActiveModel.caseActivePlus,
  //                 bottomRightTodayText: snapshot.data![7][3].cardActiveModel.caseActiveToday,
  //                 bottomRightUpOrDown: snapshot.data![7][3].cardActiveModel.caseActiveArrow,
  //                 bottomRightPercentage: snapshot.data![7][3].cardActiveModel.caseActivePercent,
  //                 bottomRightDate: widget.time,
  //               ),
  //               StatisticsStatesItems(
  //                 titleText: 'Perlis',
  //                 // TOP LEFT
  //                 topLeftColor: kStatisticRed,
  //                 topLeftHeader: 'Total Confirmed Cases',
  //                 topLeftTotalText: snapshot.data![8][0].cardConfirmedModel.caseConfirmed,
  //                 topLeftPlusOrMinus: snapshot.data![8][0].cardConfirmedModel.caseConfirmedPlus,
  //                 topLeftTodayText: snapshot.data![8][0].cardConfirmedModel.caseConfirmedToday,
  //                 topLeftUpOrDown: snapshot.data![8][0].cardConfirmedModel.caseConfirmedArrow,
  //                 topLeftPercentage: snapshot.data![8][0].cardConfirmedModel.caseConfirmedPercent,
  //                 topLeftDate: widget.time,
  //                 // TOP RIGHT
  //                 topRightColor: kStatisticGreen,
  //                 topRightHeader: 'Total Recovered',
  //                 topRightTotalText: snapshot.data![8][1].cardRecoveredModel.caseRecovered,
  //                 topRightPlusOrMinus: snapshot.data![8][1].cardRecoveredModel.caseRecoveredPlus,
  //                 topRightTodayText: snapshot.data![8][1].cardRecoveredModel.caseRecoveredToday,
  //                 topRightUpOrDown: snapshot.data![8][1].cardRecoveredModel.caseRecoveredArrow,
  //                 topRightPercentage: snapshot.data![8][1].cardRecoveredModel.caseRecoveredPercent,
  //                 topRightDate: widget.time,
  //                 // BOTTOM LEFT
  //                 bottomLeftColor: kStatisticGrey,
  //                 bottomLeftHeader: 'Total Death',
  //                 bottomLeftTotalText: snapshot.data![8][2].cardDeathModel.caseDeath,
  //                 bottomLeftPlusOrMinus: snapshot.data![8][2].cardDeathModel.caseDeathPlus,
  //                 bottomLeftTodayText: snapshot.data![8][2].cardDeathModel.caseDeathToday,
  //                 bottomLeftUpOrDown: snapshot.data![8][2].cardDeathModel.caseDeathArrow,
  //                 bottomLeftPercentage: snapshot.data![8][2].cardDeathModel.caseDeathPercent,
  //                 bottomLeftDate: widget.time,
  //                 // BOTTOM RIGHT
  //                 bottomRightColor: kStatisticOrange,
  //                 bottomRightHeader: 'Total Active Cases',
  //                 bottomRightTotalText: snapshot.data![8][3].cardActiveModel.caseActive,
  //                 bottomRightPlusOrMinus: snapshot.data![8][3].cardActiveModel.caseActivePlus,
  //                 bottomRightTodayText: snapshot.data![8][3].cardActiveModel.caseActiveToday,
  //                 bottomRightUpOrDown: snapshot.data![8][3].cardActiveModel.caseActiveArrow,
  //                 bottomRightPercentage: snapshot.data![8][3].cardActiveModel.caseActivePercent,
  //                 bottomRightDate: widget.time,
  //               ),
  //               StatisticsStatesItems(
  //                 titleText: 'Sabah',
  //                 // TOP LEFT
  //                 topLeftColor: kStatisticRed,
  //                 topLeftHeader: 'Total Confirmed Cases',
  //                 topLeftTotalText: snapshot.data![9][0].cardConfirmedModel.caseConfirmed,
  //                 topLeftPlusOrMinus: snapshot.data![9][0].cardConfirmedModel.caseConfirmedPlus,
  //                 topLeftTodayText: snapshot.data![9][0].cardConfirmedModel.caseConfirmedToday,
  //                 topLeftUpOrDown: snapshot.data![9][0].cardConfirmedModel.caseConfirmedArrow,
  //                 topLeftPercentage: snapshot.data![9][0].cardConfirmedModel.caseConfirmedPercent,
  //                 topLeftDate: widget.time,
  //                 // TOP RIGHT
  //                 topRightColor: kStatisticGreen,
  //                 topRightHeader: 'Total Recovered',
  //                 topRightTotalText: snapshot.data![9][1].cardRecoveredModel.caseRecovered,
  //                 topRightPlusOrMinus: snapshot.data![9][1].cardRecoveredModel.caseRecoveredPlus,
  //                 topRightTodayText: snapshot.data![9][1].cardRecoveredModel.caseRecoveredToday,
  //                 topRightUpOrDown: snapshot.data![9][1].cardRecoveredModel.caseRecoveredArrow,
  //                 topRightPercentage: snapshot.data![9][1].cardRecoveredModel.caseRecoveredPercent,
  //                 topRightDate: widget.time,
  //                 // BOTTOM LEFT
  //                 bottomLeftColor: kStatisticGrey,
  //                 bottomLeftHeader: 'Total Death',
  //                 bottomLeftTotalText: snapshot.data![9][2].cardDeathModel.caseDeath,
  //                 bottomLeftPlusOrMinus: snapshot.data![9][2].cardDeathModel.caseDeathPlus,
  //                 bottomLeftTodayText: snapshot.data![9][2].cardDeathModel.caseDeathToday,
  //                 bottomLeftUpOrDown: snapshot.data![9][2].cardDeathModel.caseDeathArrow,
  //                 bottomLeftPercentage: snapshot.data![9][2].cardDeathModel.caseDeathPercent,
  //                 bottomLeftDate: widget.time,
  //                 // BOTTOM RIGHT
  //                 bottomRightColor: kStatisticOrange,
  //                 bottomRightHeader: 'Total Active Cases',
  //                 bottomRightTotalText: snapshot.data![9][3].cardActiveModel.caseActive,
  //                 bottomRightPlusOrMinus: snapshot.data![9][3].cardActiveModel.caseActivePlus,
  //                 bottomRightTodayText: snapshot.data![9][3].cardActiveModel.caseActiveToday,
  //                 bottomRightUpOrDown: snapshot.data![9][3].cardActiveModel.caseActiveArrow,
  //                 bottomRightPercentage: snapshot.data![9][3].cardActiveModel.caseActivePercent,
  //                 bottomRightDate: widget.time,
  //               ),
  //               StatisticsStatesItems(
  //                 titleText: 'Sarawak',
  //                 // TOP LEFT
  //                 topLeftColor: kStatisticRed,
  //                 topLeftHeader: 'Total Confirmed Cases',
  //                 topLeftTotalText: snapshot.data![10][0].cardConfirmedModel.caseConfirmed,
  //                 topLeftPlusOrMinus: snapshot.data![10][0].cardConfirmedModel.caseConfirmedPlus,
  //                 topLeftTodayText: snapshot.data![10][0].cardConfirmedModel.caseConfirmedToday,
  //                 topLeftUpOrDown: snapshot.data![10][0].cardConfirmedModel.caseConfirmedArrow,
  //                 topLeftPercentage: snapshot.data![10][0].cardConfirmedModel.caseConfirmedPercent,
  //                 topLeftDate: widget.time,
  //                 // TOP RIGHT
  //                 topRightColor: kStatisticGreen,
  //                 topRightHeader: 'Total Recovered',
  //                 topRightTotalText: snapshot.data![10][1].cardRecoveredModel.caseRecovered,
  //                 topRightPlusOrMinus: snapshot.data![10][1].cardRecoveredModel.caseRecoveredPlus,
  //                 topRightTodayText: snapshot.data![10][1].cardRecoveredModel.caseRecoveredToday,
  //                 topRightUpOrDown: snapshot.data![10][1].cardRecoveredModel.caseRecoveredArrow,
  //                 topRightPercentage: snapshot.data![10][1].cardRecoveredModel.caseRecoveredPercent,
  //                 topRightDate: widget.time,
  //                 // BOTTOM LEFT
  //                 bottomLeftColor: kStatisticGrey,
  //                 bottomLeftHeader: 'Total Death',
  //                 bottomLeftTotalText: snapshot.data![10][2].cardDeathModel.caseDeath,
  //                 bottomLeftPlusOrMinus: snapshot.data![10][2].cardDeathModel.caseDeathPlus,
  //                 bottomLeftTodayText: snapshot.data![10][2].cardDeathModel.caseDeathToday,
  //                 bottomLeftUpOrDown: snapshot.data![10][2].cardDeathModel.caseDeathArrow,
  //                 bottomLeftPercentage: snapshot.data![10][2].cardDeathModel.caseDeathPercent,
  //                 bottomLeftDate: widget.time,
  //                 // BOTTOM RIGHT
  //                 bottomRightColor: kStatisticOrange,
  //                 bottomRightHeader: 'Total Active Cases',
  //                 bottomRightTotalText: snapshot.data![10][3].cardActiveModel.caseActive,
  //                 bottomRightPlusOrMinus: snapshot.data![10][3].cardActiveModel.caseActivePlus,
  //                 bottomRightTodayText: snapshot.data![10][3].cardActiveModel.caseActiveToday,
  //                 bottomRightUpOrDown: snapshot.data![10][3].cardActiveModel.caseActiveArrow,
  //                 bottomRightPercentage: snapshot.data![10][3].cardActiveModel.caseActivePercent,
  //                 bottomRightDate: widget.time,
  //               ),
  //               StatisticsStatesItems(
  //                 titleText: 'Selangor',
  //                 // TOP LEFT
  //                 topLeftColor: kStatisticRed,
  //                 topLeftHeader: 'Total Confirmed Cases',
  //                 topLeftTotalText: snapshot.data![11][0].cardConfirmedModel.caseConfirmed,
  //                 topLeftPlusOrMinus: snapshot.data![11][0].cardConfirmedModel.caseConfirmedPlus,
  //                 topLeftTodayText: snapshot.data![11][0].cardConfirmedModel.caseConfirmedToday,
  //                 topLeftUpOrDown: snapshot.data![11][0].cardConfirmedModel.caseConfirmedArrow,
  //                 topLeftPercentage: snapshot.data![11][0].cardConfirmedModel.caseConfirmedPercent,
  //                 topLeftDate: widget.time,
  //                 // TOP RIGHT
  //                 topRightColor: kStatisticGreen,
  //                 topRightHeader: 'Total Recovered',
  //                 topRightTotalText: snapshot.data![11][1].cardRecoveredModel.caseRecovered,
  //                 topRightPlusOrMinus: snapshot.data![11][1].cardRecoveredModel.caseRecoveredPlus,
  //                 topRightTodayText: snapshot.data![11][1].cardRecoveredModel.caseRecoveredToday,
  //                 topRightUpOrDown: snapshot.data![11][1].cardRecoveredModel.caseRecoveredArrow,
  //                 topRightPercentage: snapshot.data![11][1].cardRecoveredModel.caseRecoveredPercent,
  //                 topRightDate: widget.time,
  //                 // BOTTOM LEFT
  //                 bottomLeftColor: kStatisticGrey,
  //                 bottomLeftHeader: 'Total Death',
  //                 bottomLeftTotalText: snapshot.data![11][2].cardDeathModel.caseDeath,
  //                 bottomLeftPlusOrMinus: snapshot.data![11][2].cardDeathModel.caseDeathPlus,
  //                 bottomLeftTodayText: snapshot.data![11][2].cardDeathModel.caseDeathToday,
  //                 bottomLeftUpOrDown: snapshot.data![11][2].cardDeathModel.caseDeathArrow,
  //                 bottomLeftPercentage: snapshot.data![11][2].cardDeathModel.caseDeathPercent,
  //                 bottomLeftDate: widget.time,
  //                 // BOTTOM RIGHT
  //                 bottomRightColor: kStatisticOrange,
  //                 bottomRightHeader: 'Total Active Cases',
  //                 bottomRightTotalText: snapshot.data![11][3].cardActiveModel.caseActive,
  //                 bottomRightPlusOrMinus: snapshot.data![11][3].cardActiveModel.caseActivePlus,
  //                 bottomRightTodayText: snapshot.data![11][3].cardActiveModel.caseActiveToday,
  //                 bottomRightUpOrDown: snapshot.data![11][3].cardActiveModel.caseActiveArrow,
  //                 bottomRightPercentage: snapshot.data![11][3].cardActiveModel.caseActivePercent,
  //                 bottomRightDate: widget.time,
  //               ),
  //               StatisticsStatesItems(
  //                 titleText: 'Terengganu',
  //                 // TOP LEFT
  //                 topLeftColor: kStatisticRed,
  //                 topLeftHeader: 'Total Confirmed Cases',
  //                 topLeftTotalText: snapshot.data![12][0].cardConfirmedModel.caseConfirmed,
  //                 topLeftPlusOrMinus: snapshot.data![12][0].cardConfirmedModel.caseConfirmedPlus,
  //                 topLeftTodayText: snapshot.data![12][0].cardConfirmedModel.caseConfirmedToday,
  //                 topLeftUpOrDown: snapshot.data![12][0].cardConfirmedModel.caseConfirmedArrow,
  //                 topLeftPercentage: snapshot.data![12][0].cardConfirmedModel.caseConfirmedPercent,
  //                 topLeftDate: widget.time,
  //                 // TOP RIGHT
  //                 topRightColor: kStatisticGreen,
  //                 topRightHeader: 'Total Recovered',
  //                 topRightTotalText: snapshot.data![12][1].cardRecoveredModel.caseRecovered,
  //                 topRightPlusOrMinus: snapshot.data![12][1].cardRecoveredModel.caseRecoveredPlus,
  //                 topRightTodayText: snapshot.data![12][1].cardRecoveredModel.caseRecoveredToday,
  //                 topRightUpOrDown: snapshot.data![12][1].cardRecoveredModel.caseRecoveredArrow,
  //                 topRightPercentage: snapshot.data![12][1].cardRecoveredModel.caseRecoveredPercent,
  //                 topRightDate: widget.time,
  //                 // BOTTOM LEFT
  //                 bottomLeftColor: kStatisticGrey,
  //                 bottomLeftHeader: 'Total Death',
  //                 bottomLeftTotalText: snapshot.data![12][2].cardDeathModel.caseDeath,
  //                 bottomLeftPlusOrMinus: snapshot.data![12][2].cardDeathModel.caseDeathPlus,
  //                 bottomLeftTodayText: snapshot.data![12][2].cardDeathModel.caseDeathToday,
  //                 bottomLeftUpOrDown: snapshot.data![12][2].cardDeathModel.caseDeathArrow,
  //                 bottomLeftPercentage: snapshot.data![12][2].cardDeathModel.caseDeathPercent,
  //                 bottomLeftDate: widget.time,
  //                 // BOTTOM RIGHT
  //                 bottomRightColor: kStatisticOrange,
  //                 bottomRightHeader: 'Total Active Cases',
  //                 bottomRightTotalText: snapshot.data![12][3].cardActiveModel.caseActive,
  //                 bottomRightPlusOrMinus: snapshot.data![12][3].cardActiveModel.caseActivePlus,
  //                 bottomRightTodayText: snapshot.data![12][3].cardActiveModel.caseActiveToday,
  //                 bottomRightUpOrDown: snapshot.data![12][3].cardActiveModel.caseActiveArrow,
  //                 bottomRightPercentage: snapshot.data![12][3].cardActiveModel.caseActivePercent,
  //                 bottomRightDate: widget.time,
  //               ),
  //               StatisticsStatesItems(
  //                 titleText: 'W.P. Kuala Lumpur',
  //                 // TOP LEFT
  //                 topLeftColor: kStatisticRed,
  //                 topLeftHeader: 'Total Confirmed Cases',
  //                 topLeftTotalText: snapshot.data![13][0].cardConfirmedModel.caseConfirmed,
  //                 topLeftPlusOrMinus: snapshot.data![13][0].cardConfirmedModel.caseConfirmedPlus,
  //                 topLeftTodayText: snapshot.data![13][0].cardConfirmedModel.caseConfirmedToday,
  //                 topLeftUpOrDown: snapshot.data![13][0].cardConfirmedModel.caseConfirmedArrow,
  //                 topLeftPercentage: snapshot.data![13][0].cardConfirmedModel.caseConfirmedPercent,
  //                 topLeftDate: widget.time,
  //                 // TOP RIGHT
  //                 topRightColor: kStatisticGreen,
  //                 topRightHeader: 'Total Recovered',
  //                 topRightTotalText: snapshot.data![13][1].cardRecoveredModel.caseRecovered,
  //                 topRightPlusOrMinus: snapshot.data![13][1].cardRecoveredModel.caseRecoveredPlus,
  //                 topRightTodayText: snapshot.data![13][1].cardRecoveredModel.caseRecoveredToday,
  //                 topRightUpOrDown: snapshot.data![13][1].cardRecoveredModel.caseRecoveredArrow,
  //                 topRightPercentage: snapshot.data![13][1].cardRecoveredModel.caseRecoveredPercent,
  //                 topRightDate: widget.time,
  //                 // BOTTOM LEFT
  //                 bottomLeftColor: kStatisticGrey,
  //                 bottomLeftHeader: 'Total Death',
  //                 bottomLeftTotalText: snapshot.data![13][2].cardDeathModel.caseDeath,
  //                 bottomLeftPlusOrMinus: snapshot.data![13][2].cardDeathModel.caseDeathPlus,
  //                 bottomLeftTodayText: snapshot.data![13][2].cardDeathModel.caseDeathToday,
  //                 bottomLeftUpOrDown: snapshot.data![13][2].cardDeathModel.caseDeathArrow,
  //                 bottomLeftPercentage: snapshot.data![13][2].cardDeathModel.caseDeathPercent,
  //                 bottomLeftDate: widget.time,
  //                 // BOTTOM RIGHT
  //                 bottomRightColor: kStatisticOrange,
  //                 bottomRightHeader: 'Total Active Cases',
  //                 bottomRightTotalText: snapshot.data![13][3].cardActiveModel.caseActive,
  //                 bottomRightPlusOrMinus: snapshot.data![13][3].cardActiveModel.caseActivePlus,
  //                 bottomRightTodayText: snapshot.data![13][3].cardActiveModel.caseActiveToday,
  //                 bottomRightUpOrDown: snapshot.data![13][3].cardActiveModel.caseActiveArrow,
  //                 bottomRightPercentage: snapshot.data![13][3].cardActiveModel.caseActivePercent,
  //                 bottomRightDate: widget.time,
  //               ),
  //               StatisticsStatesItems(
  //                 titleText: 'W.P. Labuan',
  //                 // TOP LEFT
  //                 topLeftColor: kStatisticRed,
  //                 topLeftHeader: 'Total Confirmed Cases',
  //                 topLeftTotalText: snapshot.data![14][0].cardConfirmedModel.caseConfirmed,
  //                 topLeftPlusOrMinus: snapshot.data![14][0].cardConfirmedModel.caseConfirmedPlus,
  //                 topLeftTodayText: snapshot.data![14][0].cardConfirmedModel.caseConfirmedToday,
  //                 topLeftUpOrDown: snapshot.data![14][0].cardConfirmedModel.caseConfirmedArrow,
  //                 topLeftPercentage: snapshot.data![14][0].cardConfirmedModel.caseConfirmedPercent,
  //                 topLeftDate: widget.time,
  //                 // TOP RIGHT
  //                 topRightColor: kStatisticGreen,
  //                 topRightHeader: 'Total Recovered',
  //                 topRightTotalText: snapshot.data![14][1].cardRecoveredModel.caseRecovered,
  //                 topRightPlusOrMinus: snapshot.data![14][1].cardRecoveredModel.caseRecoveredPlus,
  //                 topRightTodayText: snapshot.data![14][1].cardRecoveredModel.caseRecoveredToday,
  //                 topRightUpOrDown: snapshot.data![14][1].cardRecoveredModel.caseRecoveredArrow,
  //                 topRightPercentage: snapshot.data![14][1].cardRecoveredModel.caseRecoveredPercent,
  //                 topRightDate: widget.time,
  //                 // BOTTOM LEFT
  //                 bottomLeftColor: kStatisticGrey,
  //                 bottomLeftHeader: 'Total Death',
  //                 bottomLeftTotalText: snapshot.data![14][2].cardDeathModel.caseDeath,
  //                 bottomLeftPlusOrMinus: snapshot.data![14][2].cardDeathModel.caseDeathPlus,
  //                 bottomLeftTodayText: snapshot.data![14][2].cardDeathModel.caseDeathToday,
  //                 bottomLeftUpOrDown: snapshot.data![14][2].cardDeathModel.caseDeathArrow,
  //                 bottomLeftPercentage: snapshot.data![14][2].cardDeathModel.caseDeathPercent,
  //                 bottomLeftDate: widget.time,
  //                 // BOTTOM RIGHT
  //                 bottomRightColor: kStatisticOrange,
  //                 bottomRightHeader: 'Total Active Cases',
  //                 bottomRightTotalText: snapshot.data![14][3].cardActiveModel.caseActive,
  //                 bottomRightPlusOrMinus: snapshot.data![14][3].cardActiveModel.caseActivePlus,
  //                 bottomRightTodayText: snapshot.data![14][3].cardActiveModel.caseActiveToday,
  //                 bottomRightUpOrDown: snapshot.data![14][3].cardActiveModel.caseActiveArrow,
  //                 bottomRightPercentage: snapshot.data![14][3].cardActiveModel.caseActivePercent,
  //                 bottomRightDate: widget.time,
  //               ),
  //               StatisticsStatesItems(
  //                 titleText: 'W.P. Putrajaya',
  //                 // TOP LEFT
  //                 topLeftColor: kStatisticRed,
  //                 topLeftHeader: 'Total Confirmed Cases',
  //                 topLeftTotalText: snapshot.data![15][0].cardConfirmedModel.caseConfirmed,
  //                 topLeftPlusOrMinus: snapshot.data![15][0].cardConfirmedModel.caseConfirmedPlus,
  //                 topLeftTodayText: snapshot.data![15][0].cardConfirmedModel.caseConfirmedToday,
  //                 topLeftUpOrDown: snapshot.data![15][0].cardConfirmedModel.caseConfirmedArrow,
  //                 topLeftPercentage: snapshot.data![15][0].cardConfirmedModel.caseConfirmedPercent,
  //                 topLeftDate: widget.time,
  //                 // TOP RIGHT
  //                 topRightColor: kStatisticGreen,
  //                 topRightHeader: 'Total Recovered',
  //                 topRightTotalText: snapshot.data![15][1].cardRecoveredModel.caseRecovered,
  //                 topRightPlusOrMinus: snapshot.data![15][1].cardRecoveredModel.caseRecoveredPlus,
  //                 topRightTodayText: snapshot.data![15][1].cardRecoveredModel.caseRecoveredToday,
  //                 topRightUpOrDown: snapshot.data![15][1].cardRecoveredModel.caseRecoveredArrow,
  //                 topRightPercentage: snapshot.data![15][1].cardRecoveredModel.caseRecoveredPercent,
  //                 topRightDate: widget.time,
  //                 // BOTTOM LEFT
  //                 bottomLeftColor: kStatisticGrey,
  //                 bottomLeftHeader: 'Total Death',
  //                 bottomLeftTotalText: snapshot.data![15][2].cardDeathModel.caseDeath,
  //                 bottomLeftPlusOrMinus: snapshot.data![15][2].cardDeathModel.caseDeathPlus,
  //                 bottomLeftTodayText: snapshot.data![15][2].cardDeathModel.caseDeathToday,
  //                 bottomLeftUpOrDown: snapshot.data![15][2].cardDeathModel.caseDeathArrow,
  //                 bottomLeftPercentage: snapshot.data![15][2].cardDeathModel.caseDeathPercent,
  //                 bottomLeftDate: widget.time,
  //                 // BOTTOM RIGHT
  //                 bottomRightColor: kStatisticOrange,
  //                 bottomRightHeader: 'Total Active Cases',
  //                 bottomRightTotalText: snapshot.data![15][3].cardActiveModel.caseActive,
  //                 bottomRightPlusOrMinus: snapshot.data![15][3].cardActiveModel.caseActivePlus,
  //                 bottomRightTodayText: snapshot.data![15][3].cardActiveModel.caseActiveToday,
  //                 bottomRightUpOrDown: snapshot.data![15][3].cardActiveModel.caseActiveArrow,
  //                 bottomRightPercentage: snapshot.data![15][3].cardActiveModel.caseActivePercent,
  //                 bottomRightDate: widget.time,
  //               ),
  //             ],
  //           );
  //         } else if (snapshot.connectionState == ConnectionState.waiting) {
  //           return Container(
  //             padding: const EdgeInsets.all(30),
  //             width: 50,
  //             height: 50,
  //             child: const CircularProgressIndicator(),
  //           );
  //         } else if (snapshot.hasError) {
  //           return Text('Error: ${snapshot.error}');
  //         } else {
  //           return const Text('Error, try to restart the app');
  //         }
  //       });
  // }
  StatisticsDataStates johor = StatisticsDataStates('Johor');
  StatisticsDataStates kedah = StatisticsDataStates('Kedah');
  StatisticsDataStates kelantan = StatisticsDataStates('Kelantan');
  StatisticsDataStates melaka = StatisticsDataStates('Melaka');
  StatisticsDataStates negeriSembilan = StatisticsDataStates('Negeri Sembilan');
  StatisticsDataStates pahang = StatisticsDataStates('Pahang');
  StatisticsDataStates perak = StatisticsDataStates('Perak');
  StatisticsDataStates perlis = StatisticsDataStates('Perlis');
  StatisticsDataStates pulauPinang = StatisticsDataStates('Pulau Pinang');
  StatisticsDataStates sabah = StatisticsDataStates('Sabah');
  StatisticsDataStates sarawak = StatisticsDataStates('Sarawak');
  StatisticsDataStates selangor = StatisticsDataStates('Selangor');
  StatisticsDataStates terengganu = StatisticsDataStates('Terengganu');
  StatisticsDataStates kualaLumpur = StatisticsDataStates('W.P. Kuala Lumpur');
  StatisticsDataStates labuan = StatisticsDataStates('W.P. Labuan');
  StatisticsDataStates putrajaya = StatisticsDataStates('W.P. Putrajaya');

  // TODO: Use FutureBuilder for the data

  @override
  Widget build(BuildContext context) {
    return ListView(
      children: [
        StatisticsStatesItems(
          titleText: 'Johor',
          // TOP LEFT
          topLeftColor: kStatisticRed,
          topLeftHeader: 'Total Confirmed Cases',
          topLeftTotalText: johor.caseConfirmed,
          topLeftPlusOrMinus: johor.caseConfirmedPlus,
          topLeftTodayText: johor.caseConfirmedToday,
          topLeftUpOrDown: johor.caseConfirmedArrow,
          topLeftPercentage: johor.caseConfirmedPercent,
          topLeftDate: widget.time,
          // TOP RIGHT
          topRightColor: kStatisticGreen,
          topRightHeader: 'Total Recovered',
          topRightTotalText: johor.caseRecovered,
          topRightPlusOrMinus: johor.caseRecoveredPlus,
          topRightTodayText: johor.caseRecoveredToday,
          topRightUpOrDown: johor.caseRecoveredArrow,
          topRightPercentage: johor.caseRecoveredPercent,
          topRightDate: widget.time,
          // BOTTOM LEFT
          bottomLeftColor: kStatisticGrey,
          bottomLeftHeader: 'Total Death',
          bottomLeftTotalText: johor.caseDeath,
          bottomLeftPlusOrMinus: johor.caseDeathPlus,
          bottomLeftTodayText: johor.caseDeathToday,
          bottomLeftUpOrDown: johor.caseDeathArrow,
          bottomLeftPercentage: johor.caseDeathPercent,
          bottomLeftDate: widget.time,
          // BOTTOM RIGHT
          bottomRightColor: kStatisticOrange,
          bottomRightHeader: 'Total Active Cases',
          bottomRightTotalText: johor.caseActive,
          bottomRightPlusOrMinus: johor.caseActivePlus,
          bottomRightTodayText: johor.caseActiveToday,
          bottomRightUpOrDown: johor.caseActiveArrow,
          bottomRightPercentage: johor.caseActivePercent,
          bottomRightDate: widget.time,
        ),
        StatisticsStatesItems(
          titleText: 'Kedah',
          // TOP LEFT
          topLeftColor: kStatisticRed,
          topLeftHeader: 'Total Confirmed Cases',
          topLeftTotalText: kedah.caseConfirmed,
          topLeftPlusOrMinus: kedah.caseConfirmedPlus,
          topLeftTodayText: kedah.caseConfirmedToday,
          topLeftUpOrDown: kedah.caseConfirmedArrow,
          topLeftPercentage: kedah.caseConfirmedPercent,
          topLeftDate: widget.time,
          // TOP RIGHT
          topRightColor: kStatisticGreen,
          topRightHeader: 'Total Recovered',
          topRightTotalText: kedah.caseRecovered,
          topRightPlusOrMinus: kedah.caseRecoveredPlus,
          topRightTodayText: kedah.caseRecoveredToday,
          topRightUpOrDown: kedah.caseRecoveredArrow,
          topRightPercentage: kedah.caseRecoveredPercent,
          topRightDate: widget.time,
          // BOTTOM LEFT
          bottomLeftColor: kStatisticGrey,
          bottomLeftHeader: 'Total Death',
          bottomLeftTotalText: kedah.caseDeath,
          bottomLeftPlusOrMinus: kedah.caseDeathPlus,
          bottomLeftTodayText: kedah.caseDeathToday,
          bottomLeftUpOrDown: kedah.caseDeathArrow,
          bottomLeftPercentage: kedah.caseDeathPercent,
          bottomLeftDate: widget.time,
          // BOTTOM RIGHT
          bottomRightColor: kStatisticOrange,
          bottomRightHeader: 'Total Active Cases',
          bottomRightTotalText: kedah.caseActive,
          bottomRightPlusOrMinus: kedah.caseActivePlus,
          bottomRightTodayText: kedah.caseActiveToday,
          bottomRightUpOrDown: kedah.caseActiveArrow,
          bottomRightPercentage: kedah.caseActivePercent,
          bottomRightDate: widget.time,
        ),
        StatisticsStatesItems(
          titleText: 'Kelantan',
          // TOP LEFT
          topLeftColor: kStatisticRed,
          topLeftHeader: 'Total Confirmed Cases',
          topLeftTotalText: kelantan.caseConfirmed,
          topLeftPlusOrMinus: kelantan.caseConfirmedPlus,
          topLeftTodayText: kelantan.caseConfirmedToday,
          topLeftUpOrDown: kelantan.caseConfirmedArrow,
          topLeftPercentage: kelantan.caseConfirmedPercent,
          topLeftDate: widget.time,
          // TOP RIGHT
          topRightColor: kStatisticGreen,
          topRightHeader: 'Total Recovered',
          topRightTotalText: kelantan.caseRecovered,
          topRightPlusOrMinus: kelantan.caseRecoveredPlus,
          topRightTodayText: kelantan.caseRecoveredToday,
          topRightUpOrDown: kelantan.caseRecoveredArrow,
          topRightPercentage: kelantan.caseRecoveredPercent,
          topRightDate: widget.time,
          // BOTTOM LEFT
          bottomLeftColor: kStatisticGrey,
          bottomLeftHeader: 'Total Death',
          bottomLeftTotalText: kelantan.caseDeath,
          bottomLeftPlusOrMinus: kelantan.caseDeathPlus,
          bottomLeftTodayText: kelantan.caseDeathToday,
          bottomLeftUpOrDown: kelantan.caseDeathArrow,
          bottomLeftPercentage: kelantan.caseDeathPercent,
          bottomLeftDate: widget.time,
          // BOTTOM RIGHT
          bottomRightColor: kStatisticOrange,
          bottomRightHeader: 'Total Active Cases',
          bottomRightTotalText: kelantan.caseActive,
          bottomRightPlusOrMinus: kelantan.caseActivePlus,
          bottomRightTodayText: kelantan.caseActiveToday,
          bottomRightUpOrDown: kelantan.caseActiveArrow,
          bottomRightPercentage: kelantan.caseActivePercent,
          bottomRightDate: widget.time,
        ),
        StatisticsStatesItems(
          titleText: 'Malacca',
          // TOP LEFT
          topLeftColor: kStatisticRed,
          topLeftHeader: 'Total Confirmed Cases',
          topLeftTotalText: melaka.caseConfirmed,
          topLeftPlusOrMinus: melaka.caseConfirmedPlus,
          topLeftTodayText: melaka.caseConfirmedToday,
          topLeftUpOrDown: melaka.caseConfirmedArrow,
          topLeftPercentage: melaka.caseConfirmedPercent,
          topLeftDate: widget.time,
          // TOP RIGHT
          topRightColor: kStatisticGreen,
          topRightHeader: 'Total Recovered',
          topRightTotalText: melaka.caseRecovered,
          topRightPlusOrMinus: melaka.caseRecoveredPlus,
          topRightTodayText: melaka.caseRecoveredToday,
          topRightUpOrDown: melaka.caseRecoveredArrow,
          topRightPercentage: melaka.caseRecoveredPercent,
          topRightDate: widget.time,
          // BOTTOM LEFT
          bottomLeftColor: kStatisticGrey,
          bottomLeftHeader: 'Total Death',
          bottomLeftTotalText: melaka.caseDeath,
          bottomLeftPlusOrMinus: melaka.caseDeathPlus,
          bottomLeftTodayText: melaka.caseDeathToday,
          bottomLeftUpOrDown: melaka.caseDeathArrow,
          bottomLeftPercentage: melaka.caseDeathPercent,
          bottomLeftDate: widget.time,
          // BOTTOM RIGHT
          bottomRightColor: kStatisticOrange,
          bottomRightHeader: 'Total Active Cases',
          bottomRightTotalText: melaka.caseActive,
          bottomRightPlusOrMinus: melaka.caseActivePlus,
          bottomRightTodayText: melaka.caseActiveToday,
          bottomRightUpOrDown: melaka.caseActiveArrow,
          bottomRightPercentage: melaka.caseActivePercent,
          bottomRightDate: widget.time,
        ),
        StatisticsStatesItems(
          titleText: 'Negeri Sembilan',
          // TOP LEFT
          topLeftColor: kStatisticRed,
          topLeftHeader: 'Total Confirmed Cases',
          topLeftTotalText: negeriSembilan.caseConfirmed,
          topLeftPlusOrMinus: negeriSembilan.caseConfirmedPlus,
          topLeftTodayText: negeriSembilan.caseConfirmedToday,
          topLeftUpOrDown: negeriSembilan.caseConfirmedArrow,
          topLeftPercentage: negeriSembilan.caseConfirmedPercent,
          topLeftDate: widget.time,
          // TOP RIGHT
          topRightColor: kStatisticGreen,
          topRightHeader: 'Total Recovered',
          topRightTotalText: negeriSembilan.caseRecovered,
          topRightPlusOrMinus: negeriSembilan.caseRecoveredPlus,
          topRightTodayText: negeriSembilan.caseRecoveredToday,
          topRightUpOrDown: negeriSembilan.caseRecoveredArrow,
          topRightPercentage: negeriSembilan.caseRecoveredPercent,
          topRightDate: widget.time,
          // BOTTOM LEFT
          bottomLeftColor: kStatisticGrey,
          bottomLeftHeader: 'Total Death',
          bottomLeftTotalText: negeriSembilan.caseDeath,
          bottomLeftPlusOrMinus: negeriSembilan.caseDeathPlus,
          bottomLeftTodayText: negeriSembilan.caseDeathToday,
          bottomLeftUpOrDown: negeriSembilan.caseDeathArrow,
          bottomLeftPercentage: negeriSembilan.caseDeathPercent,
          bottomLeftDate: widget.time,
          // BOTTOM RIGHT
          bottomRightColor: kStatisticOrange,
          bottomRightHeader: 'Total Active Cases',
          bottomRightTotalText: negeriSembilan.caseActive,
          bottomRightPlusOrMinus: negeriSembilan.caseActivePlus,
          bottomRightTodayText: negeriSembilan.caseActiveToday,
          bottomRightUpOrDown: negeriSembilan.caseActiveArrow,
          bottomRightPercentage: negeriSembilan.caseActivePercent,
          bottomRightDate: widget.time,
        ),
        StatisticsStatesItems(
          titleText: 'Pahang',
          // TOP LEFT
          topLeftColor: kStatisticRed,
          topLeftHeader: 'Total Confirmed Cases',
          topLeftTotalText: pahang.caseConfirmed,
          topLeftPlusOrMinus: pahang.caseConfirmedPlus,
          topLeftTodayText: pahang.caseConfirmedToday,
          topLeftUpOrDown: pahang.caseConfirmedArrow,
          topLeftPercentage: pahang.caseConfirmedPercent,
          topLeftDate: widget.time,
          // TOP RIGHT
          topRightColor: kStatisticGreen,
          topRightHeader: 'Total Recovered',
          topRightTotalText: pahang.caseRecovered,
          topRightPlusOrMinus: pahang.caseRecoveredPlus,
          topRightTodayText: pahang.caseRecoveredToday,
          topRightUpOrDown: pahang.caseRecoveredArrow,
          topRightPercentage: pahang.caseRecoveredPercent,
          topRightDate: widget.time,
          // BOTTOM LEFT
          bottomLeftColor: kStatisticGrey,
          bottomLeftHeader: 'Total Death',
          bottomLeftTotalText: pahang.caseDeath,
          bottomLeftPlusOrMinus: pahang.caseDeathPlus,
          bottomLeftTodayText: pahang.caseDeathToday,
          bottomLeftUpOrDown: pahang.caseDeathArrow,
          bottomLeftPercentage: pahang.caseDeathPercent,
          bottomLeftDate: widget.time,
          // BOTTOM RIGHT
          bottomRightColor: kStatisticOrange,
          bottomRightHeader: 'Total Active Cases',
          bottomRightTotalText: pahang.caseActive,
          bottomRightPlusOrMinus: pahang.caseActivePlus,
          bottomRightTodayText: pahang.caseActiveToday,
          bottomRightUpOrDown: pahang.caseActiveArrow,
          bottomRightPercentage: pahang.caseActivePercent,
          bottomRightDate: widget.time,
        ),
        StatisticsStatesItems(
          titleText: 'Penang',
          // TOP LEFT
          topLeftColor: kStatisticRed,
          topLeftHeader: 'Total Confirmed Cases',
          topLeftTotalText: pulauPinang.caseConfirmed,
          topLeftPlusOrMinus: pulauPinang.caseConfirmedPlus,
          topLeftTodayText: pulauPinang.caseConfirmedToday,
          topLeftUpOrDown: pulauPinang.caseConfirmedArrow,
          topLeftPercentage: pulauPinang.caseConfirmedPercent,
          topLeftDate: widget.time,
          // TOP RIGHT
          topRightColor: kStatisticGreen,
          topRightHeader: 'Total Recovered',
          topRightTotalText: pulauPinang.caseRecovered,
          topRightPlusOrMinus: pulauPinang.caseRecoveredPlus,
          topRightTodayText: pulauPinang.caseRecoveredToday,
          topRightUpOrDown: pulauPinang.caseRecoveredArrow,
          topRightPercentage: pulauPinang.caseRecoveredPercent,
          topRightDate: widget.time,
          // BOTTOM LEFT
          bottomLeftColor: kStatisticGrey,
          bottomLeftHeader: 'Total Death',
          bottomLeftTotalText: pulauPinang.caseDeath,
          bottomLeftPlusOrMinus: pulauPinang.caseDeathPlus,
          bottomLeftTodayText: pulauPinang.caseDeathToday,
          bottomLeftUpOrDown: pulauPinang.caseDeathArrow,
          bottomLeftPercentage: pulauPinang.caseDeathPercent,
          bottomLeftDate: widget.time,
          // BOTTOM RIGHT
          bottomRightColor: kStatisticOrange,
          bottomRightHeader: 'Total Active Cases',
          bottomRightTotalText: pulauPinang.caseActive,
          bottomRightPlusOrMinus: pulauPinang.caseActivePlus,
          bottomRightTodayText: pulauPinang.caseActiveToday,
          bottomRightUpOrDown: pulauPinang.caseActiveArrow,
          bottomRightPercentage: pulauPinang.caseActivePercent,
          bottomRightDate: widget.time,
        ),
        StatisticsStatesItems(
          titleText: 'Perak',
          // TOP LEFT
          topLeftColor: kStatisticRed,
          topLeftHeader: 'Total Confirmed Cases',
          topLeftTotalText: perak.caseConfirmed,
          topLeftPlusOrMinus: perak.caseConfirmedPlus,
          topLeftTodayText: perak.caseConfirmedToday,
          topLeftUpOrDown: perak.caseConfirmedArrow,
          topLeftPercentage: perak.caseConfirmedPercent,
          topLeftDate: widget.time,
          // TOP RIGHT
          topRightColor: kStatisticGreen,
          topRightHeader: 'Total Recovered',
          topRightTotalText: perak.caseRecovered,
          topRightPlusOrMinus: perak.caseRecoveredPlus,
          topRightTodayText: perak.caseRecoveredToday,
          topRightUpOrDown: perak.caseRecoveredArrow,
          topRightPercentage: perak.caseRecoveredPercent,
          topRightDate: widget.time,
          // BOTTOM LEFT
          bottomLeftColor: kStatisticGrey,
          bottomLeftHeader: 'Total Death',
          bottomLeftTotalText: perak.caseDeath,
          bottomLeftPlusOrMinus: perak.caseDeathPlus,
          bottomLeftTodayText: perak.caseDeathToday,
          bottomLeftUpOrDown: perak.caseDeathArrow,
          bottomLeftPercentage: perak.caseDeathPercent,
          bottomLeftDate: widget.time,
          // BOTTOM RIGHT
          bottomRightColor: kStatisticOrange,
          bottomRightHeader: 'Total Active Cases',
          bottomRightTotalText: perak.caseActive,
          bottomRightPlusOrMinus: perak.caseActivePlus,
          bottomRightTodayText: perak.caseActiveToday,
          bottomRightUpOrDown: perak.caseActiveArrow,
          bottomRightPercentage: perak.caseActivePercent,
          bottomRightDate: widget.time,
        ),
        StatisticsStatesItems(
          titleText: 'Perlis',
          // TOP LEFT
          topLeftColor: kStatisticRed,
          topLeftHeader: 'Total Confirmed Cases',
          topLeftTotalText: perlis.caseConfirmed,
          topLeftPlusOrMinus: perlis.caseConfirmedPlus,
          topLeftTodayText: perlis.caseConfirmedToday,
          topLeftUpOrDown: perlis.caseConfirmedArrow,
          topLeftPercentage: perlis.caseConfirmedPercent,
          topLeftDate: widget.time,
          // TOP RIGHT
          topRightColor: kStatisticGreen,
          topRightHeader: 'Total Recovered',
          topRightTotalText: perlis.caseRecovered,
          topRightPlusOrMinus: perlis.caseRecoveredPlus,
          topRightTodayText: perlis.caseRecoveredToday,
          topRightUpOrDown: perlis.caseRecoveredArrow,
          topRightPercentage: perlis.caseRecoveredPercent,
          topRightDate: widget.time,
          // BOTTOM LEFT
          bottomLeftColor: kStatisticGrey,
          bottomLeftHeader: 'Total Death',
          bottomLeftTotalText: perlis.caseDeath,
          bottomLeftPlusOrMinus: perlis.caseDeathPlus,
          bottomLeftTodayText: perlis.caseDeathToday,
          bottomLeftUpOrDown: perlis.caseDeathArrow,
          bottomLeftPercentage: perlis.caseDeathPercent,
          bottomLeftDate: widget.time,
          // BOTTOM RIGHT
          bottomRightColor: kStatisticOrange,
          bottomRightHeader: 'Total Active Cases',
          bottomRightTotalText: perlis.caseActive,
          bottomRightPlusOrMinus: perlis.caseActivePlus,
          bottomRightTodayText: perlis.caseActiveToday,
          bottomRightUpOrDown: perlis.caseActiveArrow,
          bottomRightPercentage: perlis.caseActivePercent,
          bottomRightDate: widget.time,
        ),
        StatisticsStatesItems(
          titleText: 'Sabah',
          // TOP LEFT
          topLeftColor: kStatisticRed,
          topLeftHeader: 'Total Confirmed Cases',
          topLeftTotalText: sabah.caseConfirmed,
          topLeftPlusOrMinus: sabah.caseConfirmedPlus,
          topLeftTodayText: sabah.caseConfirmedToday,
          topLeftUpOrDown: sabah.caseConfirmedArrow,
          topLeftPercentage: sabah.caseConfirmedPercent,
          topLeftDate: widget.time,
          // TOP RIGHT
          topRightColor: kStatisticGreen,
          topRightHeader: 'Total Recovered',
          topRightTotalText: sabah.caseRecovered,
          topRightPlusOrMinus: sabah.caseRecoveredPlus,
          topRightTodayText: sabah.caseRecoveredToday,
          topRightUpOrDown: sabah.caseRecoveredArrow,
          topRightPercentage: sabah.caseRecoveredPercent,
          topRightDate: widget.time,
          // BOTTOM LEFT
          bottomLeftColor: kStatisticGrey,
          bottomLeftHeader: 'Total Death',
          bottomLeftTotalText: sabah.caseDeath,
          bottomLeftPlusOrMinus: sabah.caseDeathPlus,
          bottomLeftTodayText: sabah.caseDeathToday,
          bottomLeftUpOrDown: sabah.caseDeathArrow,
          bottomLeftPercentage: sabah.caseDeathPercent,
          bottomLeftDate: widget.time,
          // BOTTOM RIGHT
          bottomRightColor: kStatisticOrange,
          bottomRightHeader: 'Total Active Cases',
          bottomRightTotalText: sabah.caseActive,
          bottomRightPlusOrMinus: sabah.caseActivePlus,
          bottomRightTodayText: sabah.caseActiveToday,
          bottomRightUpOrDown: sabah.caseActiveArrow,
          bottomRightPercentage: sabah.caseActivePercent,
          bottomRightDate: widget.time,
        ),
        StatisticsStatesItems(
          titleText: 'Sarawak',
          // TOP LEFT
          topLeftColor: kStatisticRed,
          topLeftHeader: 'Total Confirmed Cases',
          topLeftTotalText: sarawak.caseConfirmed,
          topLeftPlusOrMinus: sarawak.caseConfirmedPlus,
          topLeftTodayText: sarawak.caseConfirmedToday,
          topLeftUpOrDown: sarawak.caseConfirmedArrow,
          topLeftPercentage: sarawak.caseConfirmedPercent,
          topLeftDate: widget.time,
          // TOP RIGHT
          topRightColor: kStatisticGreen,
          topRightHeader: 'Total Recovered',
          topRightTotalText: sarawak.caseRecovered,
          topRightPlusOrMinus: sarawak.caseRecoveredPlus,
          topRightTodayText: sarawak.caseRecoveredToday,
          topRightUpOrDown: sarawak.caseRecoveredArrow,
          topRightPercentage: sarawak.caseRecoveredPercent,
          topRightDate: widget.time,
          // BOTTOM LEFT
          bottomLeftColor: kStatisticGrey,
          bottomLeftHeader: 'Total Death',
          bottomLeftTotalText: sarawak.caseDeath,
          bottomLeftPlusOrMinus: sarawak.caseDeathPlus,
          bottomLeftTodayText: sarawak.caseDeathToday,
          bottomLeftUpOrDown: sarawak.caseDeathArrow,
          bottomLeftPercentage: sarawak.caseDeathPercent,
          bottomLeftDate: widget.time,
          // BOTTOM RIGHT
          bottomRightColor: kStatisticOrange,
          bottomRightHeader: 'Total Active Cases',
          bottomRightTotalText: sarawak.caseActive,
          bottomRightPlusOrMinus: sarawak.caseActivePlus,
          bottomRightTodayText: sarawak.caseActiveToday,
          bottomRightUpOrDown: sarawak.caseActiveArrow,
          bottomRightPercentage: sarawak.caseActivePercent,
          bottomRightDate: widget.time,
        ),
        StatisticsStatesItems(
          titleText: 'Selangor',
          // TOP LEFT
          topLeftColor: kStatisticRed,
          topLeftHeader: 'Total Confirmed Cases',
          topLeftTotalText: selangor.caseConfirmed,
          topLeftPlusOrMinus: selangor.caseConfirmedPlus,
          topLeftTodayText: selangor.caseConfirmedToday,
          topLeftUpOrDown: selangor.caseConfirmedArrow,
          topLeftPercentage: selangor.caseConfirmedPercent,
          topLeftDate: widget.time,
          // TOP RIGHT
          topRightColor: kStatisticGreen,
          topRightHeader: 'Total Recovered',
          topRightTotalText: selangor.caseRecovered,
          topRightPlusOrMinus: selangor.caseRecoveredPlus,
          topRightTodayText: selangor.caseRecoveredToday,
          topRightUpOrDown: selangor.caseRecoveredArrow,
          topRightPercentage: selangor.caseRecoveredPercent,
          topRightDate: widget.time,
          // BOTTOM LEFT
          bottomLeftColor: kStatisticGrey,
          bottomLeftHeader: 'Total Death',
          bottomLeftTotalText: selangor.caseDeath,
          bottomLeftPlusOrMinus: selangor.caseDeathPlus,
          bottomLeftTodayText: selangor.caseDeathToday,
          bottomLeftUpOrDown: selangor.caseDeathArrow,
          bottomLeftPercentage: selangor.caseDeathPercent,
          bottomLeftDate: widget.time,
          // BOTTOM RIGHT
          bottomRightColor: kStatisticOrange,
          bottomRightHeader: 'Total Active Cases',
          bottomRightTotalText: selangor.caseActive,
          bottomRightPlusOrMinus: selangor.caseActivePlus,
          bottomRightTodayText: selangor.caseActiveToday,
          bottomRightUpOrDown: selangor.caseActiveArrow,
          bottomRightPercentage: selangor.caseActivePercent,
          bottomRightDate: widget.time,
        ),
        StatisticsStatesItems(
          titleText: 'Terengganu',
          // TOP LEFT
          topLeftColor: kStatisticRed,
          topLeftHeader: 'Total Confirmed Cases',
          topLeftTotalText: terengganu.caseConfirmed,
          topLeftPlusOrMinus: terengganu.caseConfirmedPlus,
          topLeftTodayText: terengganu.caseConfirmedToday,
          topLeftUpOrDown: terengganu.caseConfirmedArrow,
          topLeftPercentage: terengganu.caseConfirmedPercent,
          topLeftDate: widget.time,
          // TOP RIGHT
          topRightColor: kStatisticGreen,
          topRightHeader: 'Total Recovered',
          topRightTotalText: terengganu.caseRecovered,
          topRightPlusOrMinus: terengganu.caseRecoveredPlus,
          topRightTodayText: terengganu.caseRecoveredToday,
          topRightUpOrDown: terengganu.caseRecoveredArrow,
          topRightPercentage: terengganu.caseRecoveredPercent,
          topRightDate: widget.time,
          // BOTTOM LEFT
          bottomLeftColor: kStatisticGrey,
          bottomLeftHeader: 'Total Death',
          bottomLeftTotalText: terengganu.caseDeath,
          bottomLeftPlusOrMinus: terengganu.caseDeathPlus,
          bottomLeftTodayText: terengganu.caseDeathToday,
          bottomLeftUpOrDown: terengganu.caseDeathArrow,
          bottomLeftPercentage: terengganu.caseDeathPercent,
          bottomLeftDate: widget.time,
          // BOTTOM RIGHT
          bottomRightColor: kStatisticOrange,
          bottomRightHeader: 'Total Active Cases',
          bottomRightTotalText: terengganu.caseActive,
          bottomRightPlusOrMinus: terengganu.caseActivePlus,
          bottomRightTodayText: terengganu.caseActiveToday,
          bottomRightUpOrDown: terengganu.caseActiveArrow,
          bottomRightPercentage: terengganu.caseActivePercent,
          bottomRightDate: widget.time,
        ),
        StatisticsStatesItems(
          titleText: 'W.P. Kuala Lumpur',
          // TOP LEFT
          topLeftColor: kStatisticRed,
          topLeftHeader: 'Total Confirmed Cases',
          topLeftTotalText: kualaLumpur.caseConfirmed,
          topLeftPlusOrMinus: kualaLumpur.caseConfirmedPlus,
          topLeftTodayText: kualaLumpur.caseConfirmedToday,
          topLeftUpOrDown: kualaLumpur.caseConfirmedArrow,
          topLeftPercentage: kualaLumpur.caseConfirmedPercent,
          topLeftDate: widget.time,
          // TOP RIGHT
          topRightColor: kStatisticGreen,
          topRightHeader: 'Total Recovered',
          topRightTotalText: kualaLumpur.caseRecovered,
          topRightPlusOrMinus: kualaLumpur.caseRecoveredPlus,
          topRightTodayText: kualaLumpur.caseRecoveredToday,
          topRightUpOrDown: kualaLumpur.caseRecoveredArrow,
          topRightPercentage: kualaLumpur.caseRecoveredPercent,
          topRightDate: widget.time,
          // BOTTOM LEFT
          bottomLeftColor: kStatisticGrey,
          bottomLeftHeader: 'Total Death',
          bottomLeftTotalText: kualaLumpur.caseDeath,
          bottomLeftPlusOrMinus: kualaLumpur.caseDeathPlus,
          bottomLeftTodayText: kualaLumpur.caseDeathToday,
          bottomLeftUpOrDown: kualaLumpur.caseDeathArrow,
          bottomLeftPercentage: kualaLumpur.caseDeathPercent,
          bottomLeftDate: widget.time,
          // BOTTOM RIGHT
          bottomRightColor: kStatisticOrange,
          bottomRightHeader: 'Total Active Cases',
          bottomRightTotalText: kualaLumpur.caseActive,
          bottomRightPlusOrMinus: kualaLumpur.caseActivePlus,
          bottomRightTodayText: kualaLumpur.caseActiveToday,
          bottomRightUpOrDown: kualaLumpur.caseActiveArrow,
          bottomRightPercentage: kualaLumpur.caseActivePercent,
          bottomRightDate: widget.time,
        ),
        StatisticsStatesItems(
          titleText: 'W.P. Labuan',
          // TOP LEFT
          topLeftColor: kStatisticRed,
          topLeftHeader: 'Total Confirmed Cases',
          topLeftTotalText: labuan.caseConfirmed,
          topLeftPlusOrMinus: labuan.caseConfirmedPlus,
          topLeftTodayText: labuan.caseConfirmedToday,
          topLeftUpOrDown: labuan.caseConfirmedArrow,
          topLeftPercentage: labuan.caseConfirmedPercent,
          topLeftDate: widget.time,
          // TOP RIGHT
          topRightColor: kStatisticGreen,
          topRightHeader: 'Total Recovered',
          topRightTotalText: labuan.caseRecovered,
          topRightPlusOrMinus: labuan.caseRecoveredPlus,
          topRightTodayText: labuan.caseRecoveredToday,
          topRightUpOrDown: labuan.caseRecoveredArrow,
          topRightPercentage: labuan.caseRecoveredPercent,
          topRightDate: widget.time,
          // BOTTOM LEFT
          bottomLeftColor: kStatisticGrey,
          bottomLeftHeader: 'Total Death',
          bottomLeftTotalText: labuan.caseDeath,
          bottomLeftPlusOrMinus: labuan.caseDeathPlus,
          bottomLeftTodayText: labuan.caseDeathToday,
          bottomLeftUpOrDown: labuan.caseDeathArrow,
          bottomLeftPercentage: labuan.caseDeathPercent,
          bottomLeftDate: widget.time,
          // BOTTOM RIGHT
          bottomRightColor: kStatisticOrange,
          bottomRightHeader: 'Total Active Cases',
          bottomRightTotalText: labuan.caseActive,
          bottomRightPlusOrMinus: labuan.caseActivePlus,
          bottomRightTodayText: labuan.caseActiveToday,
          bottomRightUpOrDown: labuan.caseActiveArrow,
          bottomRightPercentage: labuan.caseActivePercent,
          bottomRightDate: widget.time,
        ),
        StatisticsStatesItems(
          titleText: 'W.P. Putrajaya',
          // TOP LEFT
          topLeftColor: kStatisticRed,
          topLeftHeader: 'Total Confirmed Cases',
          topLeftTotalText: putrajaya.caseConfirmed,
          topLeftPlusOrMinus: putrajaya.caseConfirmedPlus,
          topLeftTodayText: putrajaya.caseConfirmedToday,
          topLeftUpOrDown: putrajaya.caseConfirmedArrow,
          topLeftPercentage: putrajaya.caseConfirmedPercent,
          topLeftDate: widget.time,
          // TOP RIGHT
          topRightColor: kStatisticGreen,
          topRightHeader: 'Total Recovered',
          topRightTotalText: putrajaya.caseRecovered,
          topRightPlusOrMinus: putrajaya.caseRecoveredPlus,
          topRightTodayText: putrajaya.caseRecoveredToday,
          topRightUpOrDown: putrajaya.caseRecoveredArrow,
          topRightPercentage: putrajaya.caseRecoveredPercent,
          topRightDate: widget.time,
          // BOTTOM LEFT
          bottomLeftColor: kStatisticGrey,
          bottomLeftHeader: 'Total Death',
          bottomLeftTotalText: putrajaya.caseDeath,
          bottomLeftPlusOrMinus: putrajaya.caseDeathPlus,
          bottomLeftTodayText: putrajaya.caseDeathToday,
          bottomLeftUpOrDown: putrajaya.caseDeathArrow,
          bottomLeftPercentage: putrajaya.caseDeathPercent,
          bottomLeftDate: widget.time,
          // BOTTOM RIGHT
          bottomRightColor: kStatisticOrange,
          bottomRightHeader: 'Total Active Cases',
          bottomRightTotalText: putrajaya.caseActive,
          bottomRightPlusOrMinus: putrajaya.caseActivePlus,
          bottomRightTodayText: putrajaya.caseActiveToday,
          bottomRightUpOrDown: putrajaya.caseActiveArrow,
          bottomRightPercentage: putrajaya.caseActivePercent,
          bottomRightDate: widget.time,
        ),
      ],
    );
  }
}
