import 'package:flutter/material.dart';

import '../helper/constant.dart';
import 'statistics_states_items.dart';

class StatisticsStates extends StatelessWidget {
  const StatisticsStates({
    Key? key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return ListView(
      children: const [
        StatisticsStatesItems(
          titleText: 'Johor',
          // TOP LEFT
          topLeftColor: kStatisticRed,
          topLeftHeader: 'Total Confirmed Cases',
          topLeftTotalText: '2,323,478',
          topLeftPlusOrMinus: Icons.add_rounded,
          topLeftTodayText: '9751',
          topLeftUpOrDown: Icons.arrow_downward_rounded,
          topLeftPercentage: '12',
          topLeftDate: '29 Jan, 2022, 11:59 PM',
          // TOP RIGHT
          topRightColor: kStatisticGreen,
          topRightHeader: 'Total Recovered',
          topRightTotalText: '2,170,288',
          topRightPlusOrMinus: Icons.add_rounded,
          topRightTodayText: '12723',
          topRightUpOrDown: Icons.arrow_upward_rounded,
          topRightPercentage: '8',
          topRightDate: '29 Jan, 2022, 11:59 PM',
          // BOTTOM LEFT
          bottomLeftColor: kStatisticGrey,
          bottomLeftHeader: 'Total Death',
          bottomLeftTotalText: '27,191',
          bottomLeftPlusOrMinus: Icons.add_rounded,
          bottomLeftTodayText: '78',
          bottomLeftUpOrDown: Icons.arrow_downward_rounded,
          bottomLeftPercentage: '3',
          bottomLeftDate: '29 Jan, 2022, 11:59 PM',
          // BOTTOM RIGHT
          bottomRightColor: kStatisticOrange,
          bottomRightHeader: 'Total Active Cases',
          bottomRightTotalText: '125,999',
          bottomRightPlusOrMinus: Icons.remove_rounded,
          bottomRightTodayText: '9751',
          bottomRightUpOrDown: Icons.arrow_upward_rounded,
          bottomRightPercentage: '12',
          bottomRightDate: '29 Jan, 2022, 11:59 PM',
        ),
        StatisticsStatesItems(
          titleText: 'Kedah',
          // TOP LEFT
          topLeftColor: kStatisticRed,
          topLeftHeader: 'Total Confirmed Cases',
          topLeftTotalText: '2,323,478',
          topLeftPlusOrMinus: Icons.add_rounded,
          topLeftTodayText: '9751',
          topLeftUpOrDown: Icons.arrow_downward_rounded,
          topLeftPercentage: '12',
          topLeftDate: '29 Jan, 2022, 11:59 PM',
          // TOP RIGHT
          topRightColor: kStatisticGreen,
          topRightHeader: 'Total Recovered',
          topRightTotalText: '2,170,288',
          topRightPlusOrMinus: Icons.add_rounded,
          topRightTodayText: '12723',
          topRightUpOrDown: Icons.arrow_upward_rounded,
          topRightPercentage: '8',
          topRightDate: '29 Jan, 2022, 11:59 PM',
          // BOTTOM LEFT
          bottomLeftColor: kStatisticGrey,
          bottomLeftHeader: 'Total Death',
          bottomLeftTotalText: '27,191',
          bottomLeftPlusOrMinus: Icons.add_rounded,
          bottomLeftTodayText: '78',
          bottomLeftUpOrDown: Icons.arrow_downward_rounded,
          bottomLeftPercentage: '3',
          bottomLeftDate: '29 Jan, 2022, 11:59 PM',
          // BOTTOM RIGHT
          bottomRightColor: kStatisticOrange,
          bottomRightHeader: 'Total Active Cases',
          bottomRightTotalText: '125,999',
          bottomRightPlusOrMinus: Icons.remove_rounded,
          bottomRightTodayText: '9751',
          bottomRightUpOrDown: Icons.arrow_upward_rounded,
          bottomRightPercentage: '12',
          bottomRightDate: '29 Jan, 2022, 11:59 PM',
        ),
        StatisticsStatesItems(
          titleText: 'Kelantan',
          // TOP LEFT
          topLeftColor: kStatisticRed,
          topLeftHeader: 'Total Confirmed Cases',
          topLeftTotalText: '2,323,478',
          topLeftPlusOrMinus: Icons.add_rounded,
          topLeftTodayText: '9751',
          topLeftUpOrDown: Icons.arrow_downward_rounded,
          topLeftPercentage: '12',
          topLeftDate: '29 Jan, 2022, 11:59 PM',
          // TOP RIGHT
          topRightColor: kStatisticGreen,
          topRightHeader: 'Total Recovered',
          topRightTotalText: '2,170,288',
          topRightPlusOrMinus: Icons.add_rounded,
          topRightTodayText: '12723',
          topRightUpOrDown: Icons.arrow_upward_rounded,
          topRightPercentage: '8',
          topRightDate: '29 Jan, 2022, 11:59 PM',
          // BOTTOM LEFT
          bottomLeftColor: kStatisticGrey,
          bottomLeftHeader: 'Total Death',
          bottomLeftTotalText: '27,191',
          bottomLeftPlusOrMinus: Icons.add_rounded,
          bottomLeftTodayText: '78',
          bottomLeftUpOrDown: Icons.arrow_downward_rounded,
          bottomLeftPercentage: '3',
          bottomLeftDate: '29 Jan, 2022, 11:59 PM',
          // BOTTOM RIGHT
          bottomRightColor: kStatisticOrange,
          bottomRightHeader: 'Total Active Cases',
          bottomRightTotalText: '125,999',
          bottomRightPlusOrMinus: Icons.remove_rounded,
          bottomRightTodayText: '9751',
          bottomRightUpOrDown: Icons.arrow_upward_rounded,
          bottomRightPercentage: '12',
          bottomRightDate: '29 Jan, 2022, 11:59 PM',
        ),
        StatisticsStatesItems(
          titleText: 'Malacca',
          // TOP LEFT
          topLeftColor: kStatisticRed,
          topLeftHeader: 'Total Confirmed Cases',
          topLeftTotalText: '2,323,478',
          topLeftPlusOrMinus: Icons.add_rounded,
          topLeftTodayText: '9751',
          topLeftUpOrDown: Icons.arrow_downward_rounded,
          topLeftPercentage: '12',
          topLeftDate: '29 Jan, 2022, 11:59 PM',
          // TOP RIGHT
          topRightColor: kStatisticGreen,
          topRightHeader: 'Total Recovered',
          topRightTotalText: '2,170,288',
          topRightPlusOrMinus: Icons.add_rounded,
          topRightTodayText: '12723',
          topRightUpOrDown: Icons.arrow_upward_rounded,
          topRightPercentage: '8',
          topRightDate: '29 Jan, 2022, 11:59 PM',
          // BOTTOM LEFT
          bottomLeftColor: kStatisticGrey,
          bottomLeftHeader: 'Total Death',
          bottomLeftTotalText: '27,191',
          bottomLeftPlusOrMinus: Icons.add_rounded,
          bottomLeftTodayText: '78',
          bottomLeftUpOrDown: Icons.arrow_downward_rounded,
          bottomLeftPercentage: '3',
          bottomLeftDate: '29 Jan, 2022, 11:59 PM',
          // BOTTOM RIGHT
          bottomRightColor: kStatisticOrange,
          bottomRightHeader: 'Total Active Cases',
          bottomRightTotalText: '125,999',
          bottomRightPlusOrMinus: Icons.remove_rounded,
          bottomRightTodayText: '9751',
          bottomRightUpOrDown: Icons.arrow_upward_rounded,
          bottomRightPercentage: '12',
          bottomRightDate: '29 Jan, 2022, 11:59 PM',
        ),
        StatisticsStatesItems(
          titleText: 'Negeri Sembilan',
          // TOP LEFT
          topLeftColor: kStatisticRed,
          topLeftHeader: 'Total Confirmed Cases',
          topLeftTotalText: '2,323,478',
          topLeftPlusOrMinus: Icons.add_rounded,
          topLeftTodayText: '9751',
          topLeftUpOrDown: Icons.arrow_downward_rounded,
          topLeftPercentage: '12',
          topLeftDate: '29 Jan, 2022, 11:59 PM',
          // TOP RIGHT
          topRightColor: kStatisticGreen,
          topRightHeader: 'Total Recovered',
          topRightTotalText: '2,170,288',
          topRightPlusOrMinus: Icons.add_rounded,
          topRightTodayText: '12723',
          topRightUpOrDown: Icons.arrow_upward_rounded,
          topRightPercentage: '8',
          topRightDate: '29 Jan, 2022, 11:59 PM',
          // BOTTOM LEFT
          bottomLeftColor: kStatisticGrey,
          bottomLeftHeader: 'Total Death',
          bottomLeftTotalText: '27,191',
          bottomLeftPlusOrMinus: Icons.add_rounded,
          bottomLeftTodayText: '78',
          bottomLeftUpOrDown: Icons.arrow_downward_rounded,
          bottomLeftPercentage: '3',
          bottomLeftDate: '29 Jan, 2022, 11:59 PM',
          // BOTTOM RIGHT
          bottomRightColor: kStatisticOrange,
          bottomRightHeader: 'Total Active Cases',
          bottomRightTotalText: '125,999',
          bottomRightPlusOrMinus: Icons.remove_rounded,
          bottomRightTodayText: '9751',
          bottomRightUpOrDown: Icons.arrow_upward_rounded,
          bottomRightPercentage: '12',
          bottomRightDate: '29 Jan, 2022, 11:59 PM',
        ),
        StatisticsStatesItems(
          titleText: 'Pahang',
          // TOP LEFT
          topLeftColor: kStatisticRed,
          topLeftHeader: 'Total Confirmed Cases',
          topLeftTotalText: '2,323,478',
          topLeftPlusOrMinus: Icons.add_rounded,
          topLeftTodayText: '9751',
          topLeftUpOrDown: Icons.arrow_downward_rounded,
          topLeftPercentage: '12',
          topLeftDate: '29 Jan, 2022, 11:59 PM',
          // TOP RIGHT
          topRightColor: kStatisticGreen,
          topRightHeader: 'Total Recovered',
          topRightTotalText: '2,170,288',
          topRightPlusOrMinus: Icons.add_rounded,
          topRightTodayText: '12723',
          topRightUpOrDown: Icons.arrow_upward_rounded,
          topRightPercentage: '8',
          topRightDate: '29 Jan, 2022, 11:59 PM',
          // BOTTOM LEFT
          bottomLeftColor: kStatisticGrey,
          bottomLeftHeader: 'Total Death',
          bottomLeftTotalText: '27,191',
          bottomLeftPlusOrMinus: Icons.add_rounded,
          bottomLeftTodayText: '78',
          bottomLeftUpOrDown: Icons.arrow_downward_rounded,
          bottomLeftPercentage: '3',
          bottomLeftDate: '29 Jan, 2022, 11:59 PM',
          // BOTTOM RIGHT
          bottomRightColor: kStatisticOrange,
          bottomRightHeader: 'Total Active Cases',
          bottomRightTotalText: '125,999',
          bottomRightPlusOrMinus: Icons.remove_rounded,
          bottomRightTodayText: '9751',
          bottomRightUpOrDown: Icons.arrow_upward_rounded,
          bottomRightPercentage: '12',
          bottomRightDate: '29 Jan, 2022, 11:59 PM',
        ),
        StatisticsStatesItems(
          titleText: 'Penang',
          // TOP LEFT
          topLeftColor: kStatisticRed,
          topLeftHeader: 'Total Confirmed Cases',
          topLeftTotalText: '2,323,478',
          topLeftPlusOrMinus: Icons.add_rounded,
          topLeftTodayText: '9751',
          topLeftUpOrDown: Icons.arrow_downward_rounded,
          topLeftPercentage: '12',
          topLeftDate: '29 Jan, 2022, 11:59 PM',
          // TOP RIGHT
          topRightColor: kStatisticGreen,
          topRightHeader: 'Total Recovered',
          topRightTotalText: '2,170,288',
          topRightPlusOrMinus: Icons.add_rounded,
          topRightTodayText: '12723',
          topRightUpOrDown: Icons.arrow_upward_rounded,
          topRightPercentage: '8',
          topRightDate: '29 Jan, 2022, 11:59 PM',
          // BOTTOM LEFT
          bottomLeftColor: kStatisticGrey,
          bottomLeftHeader: 'Total Death',
          bottomLeftTotalText: '27,191',
          bottomLeftPlusOrMinus: Icons.add_rounded,
          bottomLeftTodayText: '78',
          bottomLeftUpOrDown: Icons.arrow_downward_rounded,
          bottomLeftPercentage: '3',
          bottomLeftDate: '29 Jan, 2022, 11:59 PM',
          // BOTTOM RIGHT
          bottomRightColor: kStatisticOrange,
          bottomRightHeader: 'Total Active Cases',
          bottomRightTotalText: '125,999',
          bottomRightPlusOrMinus: Icons.remove_rounded,
          bottomRightTodayText: '9751',
          bottomRightUpOrDown: Icons.arrow_upward_rounded,
          bottomRightPercentage: '12',
          bottomRightDate: '29 Jan, 2022, 11:59 PM',
        ),
        StatisticsStatesItems(
          titleText: 'Perak',
          // TOP LEFT
          topLeftColor: kStatisticRed,
          topLeftHeader: 'Total Confirmed Cases',
          topLeftTotalText: '2,323,478',
          topLeftPlusOrMinus: Icons.add_rounded,
          topLeftTodayText: '9751',
          topLeftUpOrDown: Icons.arrow_downward_rounded,
          topLeftPercentage: '12',
          topLeftDate: '29 Jan, 2022, 11:59 PM',
          // TOP RIGHT
          topRightColor: kStatisticGreen,
          topRightHeader: 'Total Recovered',
          topRightTotalText: '2,170,288',
          topRightPlusOrMinus: Icons.add_rounded,
          topRightTodayText: '12723',
          topRightUpOrDown: Icons.arrow_upward_rounded,
          topRightPercentage: '8',
          topRightDate: '29 Jan, 2022, 11:59 PM',
          // BOTTOM LEFT
          bottomLeftColor: kStatisticGrey,
          bottomLeftHeader: 'Total Death',
          bottomLeftTotalText: '27,191',
          bottomLeftPlusOrMinus: Icons.add_rounded,
          bottomLeftTodayText: '78',
          bottomLeftUpOrDown: Icons.arrow_downward_rounded,
          bottomLeftPercentage: '3',
          bottomLeftDate: '29 Jan, 2022, 11:59 PM',
          // BOTTOM RIGHT
          bottomRightColor: kStatisticOrange,
          bottomRightHeader: 'Total Active Cases',
          bottomRightTotalText: '125,999',
          bottomRightPlusOrMinus: Icons.remove_rounded,
          bottomRightTodayText: '9751',
          bottomRightUpOrDown: Icons.arrow_upward_rounded,
          bottomRightPercentage: '12',
          bottomRightDate: '29 Jan, 2022, 11:59 PM',
        ),
        StatisticsStatesItems(
          titleText: 'Perlis',
          // TOP LEFT
          topLeftColor: kStatisticRed,
          topLeftHeader: 'Total Confirmed Cases',
          topLeftTotalText: '2,323,478',
          topLeftPlusOrMinus: Icons.add_rounded,
          topLeftTodayText: '9751',
          topLeftUpOrDown: Icons.arrow_downward_rounded,
          topLeftPercentage: '12',
          topLeftDate: '29 Jan, 2022, 11:59 PM',
          // TOP RIGHT
          topRightColor: kStatisticGreen,
          topRightHeader: 'Total Recovered',
          topRightTotalText: '2,170,288',
          topRightPlusOrMinus: Icons.add_rounded,
          topRightTodayText: '12723',
          topRightUpOrDown: Icons.arrow_upward_rounded,
          topRightPercentage: '8',
          topRightDate: '29 Jan, 2022, 11:59 PM',
          // BOTTOM LEFT
          bottomLeftColor: kStatisticGrey,
          bottomLeftHeader: 'Total Death',
          bottomLeftTotalText: '27,191',
          bottomLeftPlusOrMinus: Icons.add_rounded,
          bottomLeftTodayText: '78',
          bottomLeftUpOrDown: Icons.arrow_downward_rounded,
          bottomLeftPercentage: '3',
          bottomLeftDate: '29 Jan, 2022, 11:59 PM',
          // BOTTOM RIGHT
          bottomRightColor: kStatisticOrange,
          bottomRightHeader: 'Total Active Cases',
          bottomRightTotalText: '125,999',
          bottomRightPlusOrMinus: Icons.remove_rounded,
          bottomRightTodayText: '9751',
          bottomRightUpOrDown: Icons.arrow_upward_rounded,
          bottomRightPercentage: '12',
          bottomRightDate: '29 Jan, 2022, 11:59 PM',
        ),
        StatisticsStatesItems(
          titleText: 'Sabah',
          // TOP LEFT
          topLeftColor: kStatisticRed,
          topLeftHeader: 'Total Confirmed Cases',
          topLeftTotalText: '2,323,478',
          topLeftPlusOrMinus: Icons.add_rounded,
          topLeftTodayText: '9751',
          topLeftUpOrDown: Icons.arrow_downward_rounded,
          topLeftPercentage: '12',
          topLeftDate: '29 Jan, 2022, 11:59 PM',
          // TOP RIGHT
          topRightColor: kStatisticGreen,
          topRightHeader: 'Total Recovered',
          topRightTotalText: '2,170,288',
          topRightPlusOrMinus: Icons.add_rounded,
          topRightTodayText: '12723',
          topRightUpOrDown: Icons.arrow_upward_rounded,
          topRightPercentage: '8',
          topRightDate: '29 Jan, 2022, 11:59 PM',
          // BOTTOM LEFT
          bottomLeftColor: kStatisticGrey,
          bottomLeftHeader: 'Total Death',
          bottomLeftTotalText: '27,191',
          bottomLeftPlusOrMinus: Icons.add_rounded,
          bottomLeftTodayText: '78',
          bottomLeftUpOrDown: Icons.arrow_downward_rounded,
          bottomLeftPercentage: '3',
          bottomLeftDate: '29 Jan, 2022, 11:59 PM',
          // BOTTOM RIGHT
          bottomRightColor: kStatisticOrange,
          bottomRightHeader: 'Total Active Cases',
          bottomRightTotalText: '125,999',
          bottomRightPlusOrMinus: Icons.remove_rounded,
          bottomRightTodayText: '9751',
          bottomRightUpOrDown: Icons.arrow_upward_rounded,
          bottomRightPercentage: '12',
          bottomRightDate: '29 Jan, 2022, 11:59 PM',
        ),
        StatisticsStatesItems(
          titleText: 'Sarawak',
          // TOP LEFT
          topLeftColor: kStatisticRed,
          topLeftHeader: 'Total Confirmed Cases',
          topLeftTotalText: '2,323,478',
          topLeftPlusOrMinus: Icons.add_rounded,
          topLeftTodayText: '9751',
          topLeftUpOrDown: Icons.arrow_downward_rounded,
          topLeftPercentage: '12',
          topLeftDate: '29 Jan, 2022, 11:59 PM',
          // TOP RIGHT
          topRightColor: kStatisticGreen,
          topRightHeader: 'Total Recovered',
          topRightTotalText: '2,170,288',
          topRightPlusOrMinus: Icons.add_rounded,
          topRightTodayText: '12723',
          topRightUpOrDown: Icons.arrow_upward_rounded,
          topRightPercentage: '8',
          topRightDate: '29 Jan, 2022, 11:59 PM',
          // BOTTOM LEFT
          bottomLeftColor: kStatisticGrey,
          bottomLeftHeader: 'Total Death',
          bottomLeftTotalText: '27,191',
          bottomLeftPlusOrMinus: Icons.add_rounded,
          bottomLeftTodayText: '78',
          bottomLeftUpOrDown: Icons.arrow_downward_rounded,
          bottomLeftPercentage: '3',
          bottomLeftDate: '29 Jan, 2022, 11:59 PM',
          // BOTTOM RIGHT
          bottomRightColor: kStatisticOrange,
          bottomRightHeader: 'Total Active Cases',
          bottomRightTotalText: '125,999',
          bottomRightPlusOrMinus: Icons.remove_rounded,
          bottomRightTodayText: '9751',
          bottomRightUpOrDown: Icons.arrow_upward_rounded,
          bottomRightPercentage: '12',
          bottomRightDate: '29 Jan, 2022, 11:59 PM',
        ),
        StatisticsStatesItems(
          titleText: 'Selangor',
          // TOP LEFT
          topLeftColor: kStatisticRed,
          topLeftHeader: 'Total Confirmed Cases',
          topLeftTotalText: '2,323,478',
          topLeftPlusOrMinus: Icons.add_rounded,
          topLeftTodayText: '9751',
          topLeftUpOrDown: Icons.arrow_downward_rounded,
          topLeftPercentage: '12',
          topLeftDate: '29 Jan, 2022, 11:59 PM',
          // TOP RIGHT
          topRightColor: kStatisticGreen,
          topRightHeader: 'Total Recovered',
          topRightTotalText: '2,170,288',
          topRightPlusOrMinus: Icons.add_rounded,
          topRightTodayText: '12723',
          topRightUpOrDown: Icons.arrow_upward_rounded,
          topRightPercentage: '8',
          topRightDate: '29 Jan, 2022, 11:59 PM',
          // BOTTOM LEFT
          bottomLeftColor: kStatisticGrey,
          bottomLeftHeader: 'Total Death',
          bottomLeftTotalText: '27,191',
          bottomLeftPlusOrMinus: Icons.add_rounded,
          bottomLeftTodayText: '78',
          bottomLeftUpOrDown: Icons.arrow_downward_rounded,
          bottomLeftPercentage: '3',
          bottomLeftDate: '29 Jan, 2022, 11:59 PM',
          // BOTTOM RIGHT
          bottomRightColor: kStatisticOrange,
          bottomRightHeader: 'Total Active Cases',
          bottomRightTotalText: '125,999',
          bottomRightPlusOrMinus: Icons.remove_rounded,
          bottomRightTodayText: '9751',
          bottomRightUpOrDown: Icons.arrow_upward_rounded,
          bottomRightPercentage: '12',
          bottomRightDate: '29 Jan, 2022, 11:59 PM',
        ),
        StatisticsStatesItems(
          titleText: 'Terengganu',
          // TOP LEFT
          topLeftColor: kStatisticRed,
          topLeftHeader: 'Total Confirmed Cases',
          topLeftTotalText: '2,323,478',
          topLeftPlusOrMinus: Icons.add_rounded,
          topLeftTodayText: '9751',
          topLeftUpOrDown: Icons.arrow_downward_rounded,
          topLeftPercentage: '12',
          topLeftDate: '29 Jan, 2022, 11:59 PM',
          // TOP RIGHT
          topRightColor: kStatisticGreen,
          topRightHeader: 'Total Recovered',
          topRightTotalText: '2,170,288',
          topRightPlusOrMinus: Icons.add_rounded,
          topRightTodayText: '12723',
          topRightUpOrDown: Icons.arrow_upward_rounded,
          topRightPercentage: '8',
          topRightDate: '29 Jan, 2022, 11:59 PM',
          // BOTTOM LEFT
          bottomLeftColor: kStatisticGrey,
          bottomLeftHeader: 'Total Death',
          bottomLeftTotalText: '27,191',
          bottomLeftPlusOrMinus: Icons.add_rounded,
          bottomLeftTodayText: '78',
          bottomLeftUpOrDown: Icons.arrow_downward_rounded,
          bottomLeftPercentage: '3',
          bottomLeftDate: '29 Jan, 2022, 11:59 PM',
          // BOTTOM RIGHT
          bottomRightColor: kStatisticOrange,
          bottomRightHeader: 'Total Active Cases',
          bottomRightTotalText: '125,999',
          bottomRightPlusOrMinus: Icons.remove_rounded,
          bottomRightTodayText: '9751',
          bottomRightUpOrDown: Icons.arrow_upward_rounded,
          bottomRightPercentage: '12',
          bottomRightDate: '29 Jan, 2022, 11:59 PM',
        ),
        StatisticsStatesItems(
          titleText: 'W.P. Kuala Lumpur',
          // TOP LEFT
          topLeftColor: kStatisticRed,
          topLeftHeader: 'Total Confirmed Cases',
          topLeftTotalText: '2,323,478',
          topLeftPlusOrMinus: Icons.add_rounded,
          topLeftTodayText: '9751',
          topLeftUpOrDown: Icons.arrow_downward_rounded,
          topLeftPercentage: '12',
          topLeftDate: '29 Jan, 2022, 11:59 PM',
          // TOP RIGHT
          topRightColor: kStatisticGreen,
          topRightHeader: 'Total Recovered',
          topRightTotalText: '2,170,288',
          topRightPlusOrMinus: Icons.add_rounded,
          topRightTodayText: '12723',
          topRightUpOrDown: Icons.arrow_upward_rounded,
          topRightPercentage: '8',
          topRightDate: '29 Jan, 2022, 11:59 PM',
          // BOTTOM LEFT
          bottomLeftColor: kStatisticGrey,
          bottomLeftHeader: 'Total Death',
          bottomLeftTotalText: '27,191',
          bottomLeftPlusOrMinus: Icons.add_rounded,
          bottomLeftTodayText: '78',
          bottomLeftUpOrDown: Icons.arrow_downward_rounded,
          bottomLeftPercentage: '3',
          bottomLeftDate: '29 Jan, 2022, 11:59 PM',
          // BOTTOM RIGHT
          bottomRightColor: kStatisticOrange,
          bottomRightHeader: 'Total Active Cases',
          bottomRightTotalText: '125,999',
          bottomRightPlusOrMinus: Icons.remove_rounded,
          bottomRightTodayText: '9751',
          bottomRightUpOrDown: Icons.arrow_upward_rounded,
          bottomRightPercentage: '12',
          bottomRightDate: '29 Jan, 2022, 11:59 PM',
        ),
        StatisticsStatesItems(
          titleText: 'W.P. Labuan',
          // TOP LEFT
          topLeftColor: kStatisticRed,
          topLeftHeader: 'Total Confirmed Cases',
          topLeftTotalText: '2,323,478',
          topLeftPlusOrMinus: Icons.add_rounded,
          topLeftTodayText: '9751',
          topLeftUpOrDown: Icons.arrow_downward_rounded,
          topLeftPercentage: '12',
          topLeftDate: '29 Jan, 2022, 11:59 PM',
          // TOP RIGHT
          topRightColor: kStatisticGreen,
          topRightHeader: 'Total Recovered',
          topRightTotalText: '2,170,288',
          topRightPlusOrMinus: Icons.add_rounded,
          topRightTodayText: '12723',
          topRightUpOrDown: Icons.arrow_upward_rounded,
          topRightPercentage: '8',
          topRightDate: '29 Jan, 2022, 11:59 PM',
          // BOTTOM LEFT
          bottomLeftColor: kStatisticGrey,
          bottomLeftHeader: 'Total Death',
          bottomLeftTotalText: '27,191',
          bottomLeftPlusOrMinus: Icons.add_rounded,
          bottomLeftTodayText: '78',
          bottomLeftUpOrDown: Icons.arrow_downward_rounded,
          bottomLeftPercentage: '3',
          bottomLeftDate: '29 Jan, 2022, 11:59 PM',
          // BOTTOM RIGHT
          bottomRightColor: kStatisticOrange,
          bottomRightHeader: 'Total Active Cases',
          bottomRightTotalText: '125,999',
          bottomRightPlusOrMinus: Icons.remove_rounded,
          bottomRightTodayText: '9751',
          bottomRightUpOrDown: Icons.arrow_upward_rounded,
          bottomRightPercentage: '12',
          bottomRightDate: '29 Jan, 2022, 11:59 PM',
        ),
        StatisticsStatesItems(
          titleText: 'W.P. Putrajaya',
          // TOP LEFT
          topLeftColor: kStatisticRed,
          topLeftHeader: 'Total Confirmed Cases',
          topLeftTotalText: '2,323,478',
          topLeftPlusOrMinus: Icons.add_rounded,
          topLeftTodayText: '9751',
          topLeftUpOrDown: Icons.arrow_downward_rounded,
          topLeftPercentage: '12',
          topLeftDate: '29 Jan, 2022, 11:59 PM',
          // TOP RIGHT
          topRightColor: kStatisticGreen,
          topRightHeader: 'Total Recovered',
          topRightTotalText: '2,170,288',
          topRightPlusOrMinus: Icons.add_rounded,
          topRightTodayText: '12723',
          topRightUpOrDown: Icons.arrow_upward_rounded,
          topRightPercentage: '8',
          topRightDate: '29 Jan, 2022, 11:59 PM',
          // BOTTOM LEFT
          bottomLeftColor: kStatisticGrey,
          bottomLeftHeader: 'Total Death',
          bottomLeftTotalText: '27,191',
          bottomLeftPlusOrMinus: Icons.add_rounded,
          bottomLeftTodayText: '78',
          bottomLeftUpOrDown: Icons.arrow_downward_rounded,
          bottomLeftPercentage: '3',
          bottomLeftDate: '29 Jan, 2022, 11:59 PM',
          // BOTTOM RIGHT
          bottomRightColor: kStatisticOrange,
          bottomRightHeader: 'Total Active Cases',
          bottomRightTotalText: '125,999',
          bottomRightPlusOrMinus: Icons.remove_rounded,
          bottomRightTodayText: '9751',
          bottomRightUpOrDown: Icons.arrow_upward_rounded,
          bottomRightPercentage: '12',
          bottomRightDate: '29 Jan, 2022, 11:59 PM',
        ),
        
      ],
    );
  }
}
