/// Flutter icons CheckInIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CheckInIcons
///      fonts:
///       - asset: fonts/CheckInIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CheckInIcons {
  CheckInIcons._();

  static const _kFontFam = 'CheckInIcons';
  static const String? _kFontPkg = null;

  static const IconData checkin = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkout = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scanIcon = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
